=== gbif/rs.gbif.org/schema/extension.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dc="http://purl.org/dc/terms/" xmlns:ext="http://rs.gbif.org/extension/"
    targetNamespace="http://rs.gbif.org/extension/" elementFormDefault="qualified"
    attributeFormDefault="unqualified">
    <xs:import namespace="http://purl.org/dc/terms/" schemaLocation="dc.xsd"/>
    <xs:element name="extension">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="property" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:NCName" use="required">
                            <xs:annotation>
                                <xs:documentation>lowerCamelCase, whitespace less simple name for the property that can for example be used to generate XML tags or json attribute names</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="namespace" type="xs:anyURI" use="required">
                            <xs:annotation>
                                <xs:documentation>The namespace this extension belongs to</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="qualName" type="xs:anyURI" use="required">
                            <xs:annotation>
                                <xs:documentation>The fully qualified name combining the simple name with the namespace.</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="group" type="xs:string" use="optional">
                            <xs:annotation>
                                <xs:documentation>Optional group name to organise properties in extensions in case there are many</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="columnLength" type="xs:positiveInteger" default="128"/>
                        <xs:attribute name="type" type="ext:dataType" default="string" use="optional">
                            <xs:annotation>
                                <xs:documentation>The data type for the property. Defaults to a string.</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>

                        <xs:attribute name="examples" type="xs:string">
                            <xs:annotation>
                                <xs:documentation>Example content for the property. If multiple are given delimited by a semicolon</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute ref="dc:relation"/>
                        <xs:attribute ref="dc:subject" use="optional"/>
                        <xs:attribute ref="dc:description" use="optional"> </xs:attribute>
                        <xs:attribute name="thesaurus" type="xs:anyURI">
                            <xs:annotation>
                                <xs:documentation>A uri identifying a vocabulary to be used for property values</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="required" type="xs:boolean" default="false"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute ref="dc:title" use="required">
                <xs:annotation>
                    <xs:documentation>The human readable english title for the entire extension</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="name" type="xs:NCName" use="required">
                <xs:annotation>
                    <xs:documentation>Capital, whitespace less simple name for the extension that can for example be used to generate XML tags</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="namespace" type="xs:anyURI" use="required">
                <xs:annotation>
                    <xs:documentation>The namespace this extension belongs to</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="rowType" type="xs:anyURI" use="required">
                <xs:annotation>
                    <xs:documentation>The rowType is the qualified name when combined with the namespace. Double or missing slashes are removed/added when name + namespace is combined.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute ref="dc:issued" use="required">
                <xs:annotation>
                    <xs:documentation>The date that the extension (version) was officially released.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute ref="dc:description" use="optional"/>
            <xs:attribute ref="dc:relation" use="optional"/>
            <xs:attribute ref="dc:subject" use="optional"/>
        </xs:complexType>
    </xs:element>

    <!-- Enumeration of supported data types -->
    <xs:simpleType name="dataType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="string"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="decimal"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="uri"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== gbif/rs.gbif.org/sandbox/extension/measurements_or_facts.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<extension xmlns="http://rs.gbif.org/extension/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:dc="http://purl.org/dc/terms/"    
    xsi:schemaLocation="http://rs.gbif.org/extension/ http://rs.gbif.org/schema/extension.xsd"
    dc:title="Darwin Core Measurement Or Facts" 
    name="MeasurementOrFact" namespace="http://rs.tdwg.org/dwc/terms/" rowType="http://rs.tdwg.org/dwc/terms/MeasurementOrFact"
    dc:issued="2018-01-17"
    dc:subject=""
    dc:relation="http://rs.tdwg.org/dwc/terms/index.htm#measureindex"
    dc:description="Support for generic measurements or facts as defined in Darwin Core. This version adds terms in the dwciri namespace.">

    <property name='measurementID' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementID' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementID' dc:description='An identifier for the MeasurementOrFact (information pertaining to measurements, facts, characteristics, or assertions). May be a global unique identifier or an identifier specific to the data set.' examples='' required='false'/>
    <property name='measurementType' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementType' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementType' dc:description='The nature of the measurement, fact, characteristic, or assertion. Recommended best practice is to use a controlled vocabulary.' examples='"tail length", "temperature", "trap line length", "survey area", "trap type"' required='false'/>
    <property name='dwciri:measurementType' namespace='http://rs.tdwg.org/dwc/iri/' qualName='http://rs.tdwg.org/dwc/iri/measurementType' dc:description='The nature of the measurement, fact, characteristic, or assertion. Recommended best practice is to use a controlled vocabulary.' examples='"http://rs.gbif.org/vocabulary/gbif/life_stage, http://vocab.nerc.ac.uk/collection/P01/current/ODRYBM01/"' required='false'/>
    <property name='measurementValue' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementValue' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementValue' dc:description='The value of the measurement, fact, characteristic, or assertion.' examples='"45", "20", "1", "14.5", "UV-light"' required='false'/>
    <property name='dwciri:measurementValue' namespace='http://rs.tdwg.org/dwc/iri/' qualName='http://rs.tdwg.org/dwc/iri/measurementValue' dc:description='The value of the measurement, fact, characteristic, or assertion.' examples='"http://rs.gbif.org/vocabulary/gbif/life_stage/juvenile, "http://vocab.nerc.ac.uk/collection/L22/current/TOOL0653/""' required='false'/>
    <property name='measurementAccuracy' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementAccuracy' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementAccuracy' dc:description='The description of the potential error associated with the measurementValue.' examples='"0.01", "normal distribution with variation of 2 m"' required='false'/>
    <property name='measurementUnit' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementUnit' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementUnit' dc:description='The units associated with the measurementValue. Recommended best practice is to use the International System of Units (SI).' examples='"mm", "C", "km", "ha"' required='false'/>
    <property name='dwciri:measurementUnit' namespace='http://rs.tdwg.org/dwc/iri/' qualName='http://rs.tdwg.org/dwc/iri//measurementUnit' dc:description='The units associated with the measurementValue. Recommended best practice is to use the International System of Units (SI).' examples='"http://vocab.nerc.ac.uk/collection/P06/current/UMSQ/"' required='false'/>
    <property name='measurementDeterminedDate' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementDeterminedDate' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementDeterminedDate' dc:description='The date on which the MeasurementOrFact was made. Recommended best practice is to use an encoding scheme, such as ISO 8601:2004(E).' examples='"1963-03-08T14:07-0600", "2009-02-20T08:40Z", "1809-02-12", "1906-06", "1971", "2007-03-01T13:00:00Z/2008-05-11T15:30:00Z", "2007-11-13/15"' required='false'/>
    <property name='measurementDeterminedBy' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementDeterminedBy' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementDeterminedBy' dc:description='A list (concatenated and separated) of names of people, groups, or organizations who determined the value of the MeasurementOrFact.' examples='"Javier de la Torre", "Julie Woodruff; Eileen Lacey"' required='false'/>
    <property name='dwciri:measurementDeterminedBy' namespace='http://rs.tdwg.org/dwc/iri/' qualName='http://rs.tdwg.org/dwc/iri/measurementDeterminedBy' dc:description='A list (concatenated and separated) of names of people, groups, or organizations who determined the value of the MeasurementOrFact.' examples='"http://orcid.org/0000-0002-2352-5497", "https://orcid.org/0000-0001-7870-9907", "https://orcid.org/0000-0002-8442-8025"' required='false'/>
    <property name='measurementMethod' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementMethod' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementMethod' dc:description='A description of or reference to (publication, URI) the method or protocol used to determine the measurement, fact, characteristic, or assertion.' examples='"minimum convex polygon around burrow entrances" for a home range area, "barometric altimeter" for an elevation' required='false'/>
    <property name='dwciri:measurementMethod' namespace='http://rs.tdwg.org/dwc/iri/' qualName='http://rs.tdwg.org/dwc/iri/measurementMethod' dc:description='A description of or reference to (publication, URI) the method or protocol used to determine the measurement, fact, characteristic, or assertion.' examples='' required='false'/>
    <property name='measurementRemarks' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementRemarks' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementRemarks' dc:description='Comments or notes accompanying the MeasurementOrFact.' examples='tip of tail missing' required='false'/>
</extension>

=== gbif/rs.gbif.org/sandbox/extension/ChronometricAge_2018-11-13.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<extension xmlns="http://rs.gbif.org/extension/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:dc="http://purl.org/dc/terms/"    
    xmlns:dwc="http://rs.tdwg.org/dwc/terms/"    
    xmlns:zan="http://zooarchnet.org/dwc/terms/"    
    xsi:schemaLocation="http://rs.gbif.org/extension/ http://rs.gbif.org/schema/extension.xsd"
    dc:title="ChronometricAge"
    name="ChronometricAge" 
    namespace="http://zooarchnet.org/dwc/terms/" 
    rowType="http://zooarchnet.org/dwc/terms/ChronometricAge"
    dc:issued="2018-11-13"
    dc:description="Extension to Occurrence Core to capture chronometric age information."
    dc:relation="https://github.com/VertNet/dwc-chronology/blob/master/standard/vocabularies/term_versions.csv"
    dc:subject="dwc:Occurrence">
    <property 
        name="chronometricAgeID" 
        namespace="http://zooarchnet.org/dwc/terms/" 
        qualName="http://zooarchnet.org/dwc/terms/chronometricAgeID" 
        dc:description='An identifier for the set of information associated with a ChronometricAge. May be a global unique identifier or an identifier specific to the data set.' 
        examples='' 
        type="string" 
        required="true"/>
    <property 
        name='verbatimChronometricAge' 
        namespace='http://zooarchnet.org/dwc/terms/' 
        qualName='http://zooarchnet.org/dwc/terms/verbatimChronometricAge' 
        dc:description='The verbatim age for a specimen, whether reported by a dating assay, associated references, or legacy information. For example, this could be the conventional radiocarbon age as given in an AMS dating report. This could also be simply what is reported as the age of a specimen in legacy collections data.' 
        examples='27 BC to 14 AD' 
        type="string" 
        required='false'/>
    <property 
        name='verbatimChronometricAgeConversionProtocol' 
        namespace='http://zooarchnet.org/dwc/terms/' 
        qualName='http://zooarchnet.org/dwc/terms/verbatimChronometricAgeConversionProtocol' 
        dc:description='The method used for converting the verbatimChronometricAge into a chronometric age in years, as captured in the maximumChronometricAge, maximumChronometricAgeReferenceSystem, minimumChronometricAge, and minimumChronometricAgeReferenceSystem fields. For example, calibration of conventional radiocarbon age or the currently accepted age range of a cultural or geological period.' 
        examples='' 
        type="string" 
        required='false'/>
    <property 
        name='maximumChronometricAge' 
        namespace='http://zooarchnet.org/dwc/terms/' 
        qualName='http://zooarchnet.org/dwc/terms/maximumChronometricAge' 
        dc:description='Upper limit for the age of a specimen as determined by a dating method. The expected unit for this field is years. This field, if populated, must have an associated maximumChronometricAgeReferenceSystem.' 
        examples='27' 
        type="integer" 
        required='false'/>
    <property 
        name='maximumChronometricAgeReferenceSystem' 
        namespace='http://zooarchnet.org/dwc/terms/' 
        qualName='http://zooarchnet.org/dwc/terms/maximumChronometricAgeReferenceSystem' 
        dc:description='The reference system associated with the maximumChronometricAge.' 
        examples='"kya", "mya", "BP", "AD", "BCE"' 
        type="string" 
        required='false'/>
    <property 
        name='minimumChronometricAge' 
        namespace='http://zooarchnet.org/dwc/terms/' 
        qualName='http://zooarchnet.org/dwc/terms/minimumChronometricAge' 
        dc:description='Lower limit for the age of a specimen as determined by a dating method. The expected unit for this field is years. This field, if populated, must have an associated maximumChronometricAgeReferenceSystem.' 
        examples='14' 
        type="integer" 
        required='false'/>
    <property 
        name='minimumChronometricAgeReferenceSystem' 
        namespace='http://zooarchnet.org/dwc/terms/' 
        qualName='http://zooarchnet.org/dwc/terms/minimumChronometricAgeReferenceSystem' 
        dc:description='The reference system associated with the minimumChronometricAge.' 
        examples='"kya", "mya", "BP", "AD", "BCE"' 
        type="string" 
        required='false'/>
    <property 
        name='chronometricAgeUncertaintyInYears' 
        namespace='http://zooarchnet.org/dwc/terms/' 
        qualName='http://zooarchnet.org/dwc/terms/chronometricAgeUncertaintyInYears' 
        dc:description='The temporal uncertainty of the maximumChronometricAge and minimumChronometicAge, in years.' 
        examples='100' 
        type="integer" 
        required='false'/>
    <property 
        name='chronometricAgeUncertaintyMethod' 
        namespace='http://zooarchnet.org/dwc/terms/' 
        qualName='http://zooarchnet.org/dwc/terms/chronometricAgeUncertaintyMethod' 
        dc:description='The method used to generate the reported uncertainty calculations.' 
        examples='' 
        type="string" 
        required='false'/>
    <property 
        name='materialDated' 
        namespace='http://zooarchnet.org/dwc/terms/' 
        qualName='http://zooarchnet.org/dwc/terms/materialDated' 
        dc:description='A description of the material on which the chronometricAgeProtocol was actually performed, if known.' 
        examples='' 
        type="string" 
        required='false'/>
    <property 
        name="materialDatedID" 
        namespace="http://zooarchnet.org/dwc/terms/" 
        qualName="http://zooarchnet.org/dwc/terms/materialDatedID" 
        dc:description='An identifier for the material on which the chronometricAgeProtocol was performed, if applicable.' 
        examples='' 
        type="string" 
        required="false"/>
    <property 
        name='chronometricAgeProtocol' 
        namespace='http://zooarchnet.org/dwc/terms/' 
        qualName='http://zooarchnet.org/dwc/terms/chronometricAgeProtocol' 
        dc:description='A description of or reference to the methods used to determine the ChronometricAge.' 
        examples='' 
        type="string" 
        required='false'/>
    <property 
        name='chronometricAgeReferences' 
        namespace='http://zooarchnet.org/dwc/terms/' 
        qualName='http://zooarchnet.org/dwc/terms/chronometricAgeReferences' 
        dc:description='A list (concatenated and separated) of identifiers (publication, bibliographic reference, global unique identifier, URI) of literature associated with the ChronometricAge.' 
        examples='' 
        type="string" 
        required='false'/>
    <property 
        name='chronometricAgeRemarks' 
        namespace='http://zooarchnet.org/dwc/terms/' 
        qualName='http://zooarchnet.org/dwc/terms/chronometricAgeRemarks' 
        dc:description='Notes or comments about the ChronometricAge.' 
        examples='' 
        type="string" 
        required='false'/>
</extension>

=== gbif/rs.gbif.org/sandbox/extension/measurements_or_facts_2023-09-18.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='/style/human.xsl'?>
<extension xmlns='http://rs.gbif.org/extension/'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:dc='http://purl.org/dc/terms/'
    xsi:schemaLocation='http://rs.gbif.org/extension/ http://rs.gbif.org/schema/extension.xsd'
    dc:title='Darwin Core Measurement or Facts'
    name='MeasurementOrFacts' namespace='http://rs.tdwg.org/dwc/terms/'
    rowType='http://rs.tdwg.org/dwc/terms/MeasurementOrFact'
    dc:issued='2023-09-18'
    dc:subject='dwc:Occurrence dwc:Event dwc:Taxon'
    dc:relation='http://rs.tdwg.org/dwc/terms/MeasurementOrFact'
    dc:description='Extended support for multiple measurements or facts associated with a Darwin Core Occurrence, Event, or Taxon Core.'>

    <!-- MeasurementOrFact -->
    <property group='MeasurementOrFact' name='measurementID' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementID' dc:relation='https://dwc.tdwg.org/terms/#dwc:measurementID' dc:description='An identifier for the dwc:MeasurementOrFact (information pertaining to measurements, facts, characteristics, or assertions). May be a global unique identifier or an identifier specific to the data set.' comments='' examples='`9c752d22-b09a-11e8-96f8-529269fb1459`' required='false'/>
    <property group='MeasurementOrFact' name='parentMeasurementID' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/parentMeasurementID' dc:relation='https://dwc.tdwg.org/terms/#dwc:parentMeasurementID' dc:description='An identifier for a broader dwc:MeasurementOrFact that groups this and potentially other dwc:MeasurementOrFacts.' comments='May be a globally unique identifier or an identifier specific to the data set.' examples='`9c752d22-b09a-11e8-96f8-529269fb1459`; `E1_E1_O1_M1`' required='false'/>
    <property group='MeasurementOrFact' name='measurementType' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementType' dc:relation='https://dwc.tdwg.org/terms/#dwc:measurementType' dc:description='The nature of the measurement, fact, characteristic, or assertion.' comments='Recommended best practice is to use a controlled vocabulary. This term has an equivalent in the dwciri: namespace that allows only an IRI as a value, whereas this term allows for any string literal value.' examples='`tail length`; `temperature`; `trap line length`; `survey area`; `trap type`' required='true'/>
    <property group='MeasurementOrFact' name='measurementValue' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementValue' dc:relation='https://dwc.tdwg.org/terms/#dwc:measurementValue' dc:description='The value of the measurement, fact, characteristic, or assertion.' comments='This term has an equivalent in the dwciri: namespace that allows only an IRI as a value, whereas this term allows for any string literal value.' examples='`45`; `20`; `1`; `14.5`; `UV-light`' required='false'/>
    <property group='MeasurementOrFact' name='measurementAccuracy' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementAccuracy' dc:relation='https://dwc.tdwg.org/terms/#dwc:measurementAccuracy' dc:description='The description of the potential error associated with the dwc:measurementValue.' comments='' examples='`0.01`; `normal distribution with variation of 2 m`' required='false'/>
    <property group='MeasurementOrFact' name='measurementUnit' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementUnit' dc:relation='https://dwc.tdwg.org/terms/#dwc:measurementUnit' dc:description='The units associated with the dwc:measurementValue.' comments='Recommended best practice is to use the International System of Units (SI). This term has an equivalent in the dwciri: namespace that allows only an IRI as a value, whereas this term allows for any string literal value.' examples='`m`; `g`; `l`; `°C`; `mm`; `km²`; `%`; `hh:mm:ss`' required='false'/>
    <property group='MeasurementOrFact' name='measurementDeterminedBy' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementDeterminedBy' dc:relation='https://dwc.tdwg.org/terms/#dwc:measurementDeterminedBy' dc:description='A list (concatenated and separated) of names of people, groups, or organizations who determined the value of the dwc:MeasurementOrFact.' comments='Recommended best practice is to separate the values in a list with space vertical bar space (` | `). This term has an equivalent in the dwciri: namespace that allows only an IRI as a value, whereas this term allows for any string literal value.' examples='`Rob Guralnick`; `Peter Desmet | Stijn Van Hoey`' required='false'/>
    <property group='MeasurementOrFact' name='measurementDeterminedDate' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementDeterminedDate' dc:relation='https://dwc.tdwg.org/terms/#dwc:measurementDeterminedDate' dc:description='The date on which the dwc:MeasurementOrFact was made.' comments='Recommended best practice is to use a date that conforms to ISO 8601-1:2019.' examples='`1963-03-08T14:07-0600` (8 Mar 1963 at 2:07pm in the time zone six hours earlier than UTC); `2009-02-20T08:40Z` (20 February 2009 8:40am UTC); `2018-08-29T15:19` (3:19pm local time on 29 August 2018); `1809-02-12` (some time during 12 February 1809); `1906-06` (some time in June 1906); `1971` (some time in the year 1971); `2007-03-01T13:00:00Z/2008-05-11T15:30:00Z` (some time during the interval between 1 March 2007 1pm UTC and 11 May 2008 3:30pm UTC); `1900/1909` (some time during the interval between the beginning of the year 1900 and the end of the year 1909); `2007-11-13/15` (some time in the interval between 13 November 2007 and 15 November 2007)' required='false'/>
    <property group='MeasurementOrFact' name='measurementMethod' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementMethod' dc:relation='https://dwc.tdwg.org/terms/#dwc:measurementMethod' dc:description='A description of or reference to (publication, URI) the method or protocol used to determine the measurement, fact, characteristic, or assertion.' comments='This term has an equivalent in the dwciri: namespace that allows only an IRI as a value, whereas this term allows for any string literal value.' examples='`minimum convex polygon around burrow entrances` (for a home range area); `barometric altimeter` (for an elevation)' required='false'/>
    <property group='MeasurementOrFact' name='measurementRemarks' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementRemarks' dc:relation='https://dwc.tdwg.org/terms/#dwc:measurementRemarks' dc:description='Comments or notes accompanying the dwc:MeasurementOrFact.' comments='' examples='`tip of tail missing`' required='false'/>
</extension>
