=== gbif/rs.gbif.org/schema/extension.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dc="http://purl.org/dc/terms/" xmlns:ext="http://rs.gbif.org/extension/"
    targetNamespace="http://rs.gbif.org/extension/" elementFormDefault="qualified"
    attributeFormDefault="unqualified">
    <xs:import namespace="http://purl.org/dc/terms/" schemaLocation="dc.xsd"/>
    <xs:element name="extension">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="property" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:NCName" use="required">
                            <xs:annotation>
                                <xs:documentation>lowerCamelCase, whitespace less simple name for the property that can for example be used to generate XML tags or json attribute names</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="namespace" type="xs:anyURI" use="required">
                            <xs:annotation>
                                <xs:documentation>The namespace this extension belongs to</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="qualName" type="xs:anyURI" use="required">
                            <xs:annotation>
                                <xs:documentation>The fully qualified name combining the simple name with the namespace.</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="group" type="xs:string" use="optional">
                            <xs:annotation>
                                <xs:documentation>Optional group name to organise properties in extensions in case there are many</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="columnLength" type="xs:positiveInteger" default="128"/>
                        <xs:attribute name="type" type="ext:dataType" default="string" use="optional">
                            <xs:annotation>
                                <xs:documentation>The data type for the property. Defaults to a string.</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>

                        <xs:attribute name="examples" type="xs:string">
                            <xs:annotation>
                                <xs:documentation>Example content for the property. If multiple are given delimited by a semicolon</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute ref="dc:relation"/>
                        <xs:attribute ref="dc:subject" use="optional"/>
                        <xs:attribute ref="dc:description" use="optional"> </xs:attribute>
                        <xs:attribute name="thesaurus" type="xs:anyURI">
                            <xs:annotation>
                                <xs:documentation>A uri identifying a vocabulary to be used for property values</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="required" type="xs:boolean" default="false"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute ref="dc:title" use="required">
                <xs:annotation>
                    <xs:documentation>The human readable english title for the entire extension</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="name" type="xs:NCName" use="required">
                <xs:annotation>
                    <xs:documentation>Capital, whitespace less simple name for the extension that can for example be used to generate XML tags</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="namespace" type="xs:anyURI" use="required">
                <xs:annotation>
                    <xs:documentation>The namespace this extension belongs to</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="rowType" type="xs:anyURI" use="required">
                <xs:annotation>
                    <xs:documentation>The rowType is the qualified name when combined with the namespace. Double or missing slashes are removed/added when name + namespace is combined.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute ref="dc:issued" use="required">
                <xs:annotation>
                    <xs:documentation>The date that the extension (version) was officially released.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute ref="dc:description" use="optional"/>
            <xs:attribute ref="dc:relation" use="optional"/>
            <xs:attribute ref="dc:subject" use="optional"/>
        </xs:complexType>
    </xs:element>

    <!-- Enumeration of supported data types -->
    <xs:simpleType name="dataType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="string"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="decimal"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="uri"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== gbif/rs.gbif.org/sandbox/extension/germplasm/20140515/MeasurementTrait.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<extension xmlns="http://rs.gbif.org/extension/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:dc="http://purl.org/dc/terms/"    
    xsi:schemaLocation="http://rs.gbif.org/extension/ http://rs.gbif.org/schema/extension.xsd"
    dc:title="Trait descriptor (v20140515)" 
    dc:description="The Germplasm Vocabulary (Darwin Core extension for genebanks) was developed in 2009 for sharing genebank datasets using the GBIF Integrated Publishing Toolkit (IPT) from the Global Biodiversity Information Facility (GBIF). This application schema describes the trait descriptors and methodology used for collecting trait measurements for the so-called Characterization and Evaluation (C and E) data. These terms where in part developed by the EPGRIS3 group of the European Cooperative Programme for Plant Genetic Resources (ECPGR) in 2009."
    dc:relation="http://purl.org/germplasm/germplasmTerm"
    name="MeasurementTrait" 
    namespace="http://purl.org/germplasm/germplasmTerm#"
    rowType="http://purl.org/germplasm/germplasmTerm#MeasurementTrait"
    dc:issued="2014-05-15">


<!--
Software application schema for the GBIF IPT data provider software, Darwin Core extension for genebanks (DwC-germplasm).
Major update: New version based on PURL germplasm vocabulary, Dag Endresen (GBIF/NordGen), 2012-09-11.
Minor update: Updated the text, Dag Endresen, 2014-04-16.
Major update: Renamed from MeasurementMethod to MeasurementTrait, Dag Endresen, 2014-05-08
-->

    <!-- MeasurementTrait (Trait descriptor) -->
    <property name="measurementTraitID" 
      namespace="http://purl.org/germplasm/germplasmTerm#" 
      qualName="http://purl.org/germplasm/germplasmTerm#measurementTraitID" 
      dc:description="Persistent identifier for a trait descriptor used to identify the description of the measurement method. This could be the persistent URL to an external ontology where the trait term is declared."
      type="string" 
      examples="URI, DOI, LSID or similar" 
      dc:relation="http://terms.tdwg.org/wiki/germplasm:measurementTraitID"
      group="MeasurementTrait" 
      required="false"/>
    <property name="measurementTraitIdentifier" 
      namespace="http://purl.org/germplasm/germplasmTerm#" 
      qualName="http://purl.org/germplasm/germplasmTerm#measurementTraitIdentifier" 
      dc:description="Local identifier for a trait descriptor used to identify the description of the measurement method. This could be the persistent URL to an external ontology where the trait term is declared."
      type="string" 
      examples="STEMRUSTAD, BYDV, PLANTHT, AWNCOLOR" 
      dc:relation="http://terms.tdwg.org/wiki/germplasm:measurementTraitIdentifier"
      group="MeasurementTrait" 
      required="false"/>
    <property name="measurementTraitName" 
      namespace="http://purl.org/germplasm/germplasmTerm#" 
      qualName="http://purl.org/germplasm/germplasmTerm#measurementTraitName" 
      dc:description="English name used to identify the trait measurement method."
      type="string" 
      examples="stem rust susceptibility; powdery mildew susceptibility; plant height; ear density" 
      dc:relation="http://terms.tdwg.org/wiki/germplasm:measurementTraitName"
      group="MeasurementTrait" 
      required="false"/>
    <property name="measurementTraitCategory" 
      namespace="http://purl.org/germplasm/germplasmTerm#" 
      qualName="http://purl.org/germplasm/germplasmTerm#measurementTraitCategory" 
      dc:description="Classification type for the trait descriptor."
      type="string" 
      examples="agrobotanical; morphological; chemical; phenological; molecular biology; disease susceptibility/-resistance; tolerance (abiotic); utilization" 
      dc:relation="http://terms.tdwg.org/wiki/germplasm:measurementTraitCategory"
      group="MeasurementTrait" 
      required="false"/>
    <property name="measurementTraitScale" 
      namespace="http://purl.org/germplasm/germplasmTerm#" 
      qualName="http://purl.org/germplasm/germplasmTerm#measurementTraitScale"
      dc:description="Measurement scale used to score the measurement values."
      type="string" 
      examples="absolute; interval; nominal; ordinal; ratio; relative" 
      dc:relation="http://terms.tdwg.org/wiki/germplasm:measurementTraitScale"
      group="MeasurementTrait" 
      required="false"/>
    <property name="measurementTraitSource" 
      namespace="http://purl.org/germplasm/germplasmTerm#" 
      qualName="http://purl.org/germplasm/germplasmTerm#measurementTraitSource" 
      dc:description="Reference to a standard Germplasm Descriptor. For example the UPOV descriptor or the Bioversity Crop Descriptor identifier."
      type="string" 
      examples="UPOV TG/198/1 (april 2003)" 
      dc:relation="http://terms.tdwg.org/wiki/germplasm:measurementTraitSource"
      group="MeasurementTrait" 
      required="false"/>
    <property name="measurementTraitRemarks" 
      namespace="http://purl.org/germplasm/germplasmTerm#" 
      qualName="http://purl.org/germplasm/germplasmTerm#measurementTraitRemarks" 
      dc:description="Remarks related to the trait measurement method."
      type="string" 
      examples="inflorescences after cutting; measured three days after heading date" 
      dc:relation="http://terms.tdwg.org/wiki/germplasm:measurementTraitRemarks"
      group="MeasurementTrait" 
      required="false"/>

    <property name="measurementType" 
      namespace="http://rs.tdwg.org/dwc/terms/" 
      qualName="http://rs.tdwg.org/dwc/terms/measurementType" 
      dc:description="The nature of the measurement, fact, characteristic, or assertion. Recommended best practice is to use a controlled vocabulary."
      type="string" 
      examples="tail length, temperature, trap line length, survey area, trap type" 
      dc:relation="http://terms.tdwg.org/wiki/dwc:measurementType"
      group="MeasurementTrait" 
      required="false"/>
    <property name="measurementMethod" 
      namespace="http://rs.tdwg.org/dwc/terms/" 
      qualName="http://rs.tdwg.org/dwc/terms/measurementMethod" 
      dc:description="A description of or reference to (publication, URI) the method or protocol used to determine the measurement, fact, characteristic, or assertion."
      type="string" 
      examples="minimum convex polygon around burrow entrances (for a home range area), barometric altimeter" 
      dc:relation="http://terms.tdwg.org/wiki/dwc:measurementMethod"
      group="MeasurementTrait" 
      required="false"/>

</extension>

=== gbif/rs.gbif.org/extension/obis/extended_measurement_or_fact.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<extension xmlns="http://rs.gbif.org/extension/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:dc="http://purl.org/dc/terms/"    
    xsi:schemaLocation="http://rs.gbif.org/extension/ http://rs.gbif.org/schema/extension.xsd"
    dc:title="Extended Measurement Or Facts" 
    name="ExtendedMeasurementOrFact" namespace="http://rs.iobis.org/obis/terms/" rowType="http://rs.iobis.org/obis/terms/ExtendedMeasurementOrFact"
    dc:issued="2016-09-05"
    dc:subject=""
    dc:relation="http://rs.tdwg.org/dwc/terms/index.htm#measureindex"
    dc:description="Support for generic measurements or facts, extended version linking to occurrences. 
    This extension (eMoF) was developed to be used in combination with the Event Core, but is also compatible with other cores. When used with Event Core it allows to create an additional link between the eMoF and the occurrence extension. The eMoF can store measurements or facts related to a biological occurrence, environmental measurements or facts and sampling method attributes. This extension also provides the option to provide identifiers to reference a vocabulary for the measurementType, measurementValue and measurementUnit fields.">
    
    <property name='measurementID' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementID' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementID' dc:description='An identifier for the MeasurementOrFact (information pertaining to measurements, facts, characteristics, or assertions). May be a global unique identifier or an identifier specific to the data set.' examples='' required='false'/>
    <property name='occurrenceID' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/occurrenceID' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#occurrenceID' dc:description='The identifier of the occurrence the measurement or fact refers to. If not applicable, it should be left empty.' examples=''  required='false'/>
    <property name='resourceID' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/resourceID' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#resourceID' dc:description='An identifier for the resource that is the subject of the relationship.' examples='' required='false'/>
    <property name='measurementType' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementType' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementType' dc:description='The nature of the measurement, fact, characteristic, or assertion. Recommended best practice is to use a controlled vocabulary.' examples='"tail length", "temperature", "trap line length", "survey area", "trap type", "Dry weight biomass", "Sampling instrument name"  ' required='false'/>
    <property name='measurementTypeID' namespace='http://rs.iobis.org/obis/terms/' qualName='http://rs.iobis.org/obis/terms/measurementTypeID' dc:relation='' dc:description='An identifier for the measurementType (global unique identifier, URI). The identifier should reference the measurementType in a vocabulary.' examples='"http://vocab.nerc.ac.uk/collection/P01/current/ODRYBM01/"' required='false'/>
    <property name='measurementValue' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementValue' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementValue' dc:description='The value of the measurement, fact, characteristic, or assertion.' examples='"45", "20", "1", "14.5", "UV-light", "Van Veen grab"' required='false'/>
    <property name='measurementValueID' namespace='http://rs.iobis.org/obis/terms/' qualName='http://rs.iobis.org/obis/terms/measurementValueID' dc:relation='' dc:description='An identifier for facts stored in the column measurementValue (global unique identifier, URI). This identifier can reference a controlled vocabulary (e.g. for sampling instrument names, methodologies, life stages) or reference a methodology paper with a DOI. When the measurementValue refers to a value and not to a fact, the measurementvalueID has no meaning and should remain empty.' examples='"http://vocab.nerc.ac.uk/collection/L22/current/TOOL0653/", "http://vocab.nerc.ac.uk/collection/B07/current/NDT023/", "http://vocab.nerc.ac.uk/collection/S11/current/S1116/"' required='false'/>
    <property name='measurementAccuracy' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementAccuracy' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementAccuracy' dc:description='The description of the potential error associated with the measurementValue.' examples='"0.01", "normal distribution with variation of 2 m"' required='false'/>
    <property name='measurementUnit' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementUnit' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementUnit' dc:description='The units associated with the measurementValue. Recommended best practice is to use the International System of Units (SI).' examples='"mm", "C", "km", "ha"' required='false'/>
    <property name='measurementUnitID' namespace='http://rs.iobis.org/obis/terms/' qualName='http://rs.iobis.org/obis/terms/measurementUnitID' dc:relation='' dc:description='An identifier for the measurementUnit (global unique identifier, URI). The identifier should reference the measurementUnit in a vocabulary.' examples='"http://vocab.nerc.ac.uk/collection/P06/current/UMSQ/", “http://vocab.nerc.ac.uk/collection/P06/current/UCPL/”, “http://vocab.nerc.ac.uk/collection/P06/current/CMCM/”' required='false'/>
    <property name='measurementDeterminedDate' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementDeterminedDate' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementDeterminedDate' dc:description='The date on which the MeasurementOrFact was made. Recommended best practice is to use an encoding scheme, such as ISO 8601:2004(E).' examples='"1963-03-08T14:07-0600", "2009-02-20T08:40Z", "1809-02-12", "1906-06", "1971", "2007-03-01T13:00:00Z/2008-05-11T15:30:00Z", "2007-11-13/15"' required='false'/>
    <property name='measurementDeterminedBy' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementDeterminedBy' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementDeterminedBy' dc:description='A list (concatenated and separated) of names of people, groups, or organizations who determined the value of the MeasurementOrFact.' examples='"Javier de la Torre", "Julie Woodruff; Eileen Lacey"' required='false'/>
    <property name='measurementMethod' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementMethod' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementMethod' dc:description='A description of or reference to (publication, URI) the method or protocol used to determine the measurement, fact, characteristic, or assertion.' examples='"minimum convex polygon around burrow entrances" for a home range area, "barometric altimeter" for an elevation' required='false'/>
    <property name='measurementRemarks' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/measurementRemarks' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#measurementRemarks' dc:description='Comments or notes accompanying the MeasurementOrFact.' examples='tip of tail missing' required='false'/>
    
</extension>

=== gbif/rs.gbif.org/extension/zooarchnet/chronometricDate.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<extension xmlns="http://rs.gbif.org/extension/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:dc="http://purl.org/dc/terms/"    
    xmlns:dwc="http://rs.tdwg.org/dwc/terms/"    
    xmlns:zan="http://zooarchnet.org/dwc/terms/"    
    xsi:schemaLocation="http://rs.gbif.org/extension/ http://rs.gbif.org/schema/extension.xsd"
    dc:title="ChronometricDate"
    name="ChronometricDate" 
    namespace="http://zooarchnet.org/dwc/terms/" 
    rowType="http://zooarchnet.org/dwc/terms/ChronometricDate"
    dc:issued="2017-11-30"
    dc:modified="2018-05-04"
    dc:subject="dwc:Occurrence"
    dc:relation="https://github.com/VertNet/dwc-chronology/blob/master/standard/vocabularies/term_versions.csv"
    dc:description="Extension to Occurrence Core to capture chronometric dating information.">
    <property name="chronometricDateID" namespace="http://zooarchnet.org/dwc/terms/" qualName="http://zooarchnet.org/dwc/terms/chronometricDateID" dc:description='An identifier for the set of information associated with a ChronometricDate. May be a global unique identifier or an identifier specific to the data set.' examples='GUID reference to the combination of information for one ChronometricDate.' type="string" required="true"/>
    <property name='verbatimChronometricAge' namespace='http://zooarchnet.org/dwc/terms/' qualName='http://zooarchnet.org/dwc/terms/verbatimChronometricAge' dc:description='The verbatim age for a specimen, whether reported by a dating assay, associated references, or legacy information. For example, this could be the conventional radiocarbon age as given in an AMS dating report. This could also be simply what is reported as the age of a specimen in legacy collections data.' examples='27 BC to 14 AD' type="string" required='false'/>
    <property name='verbatimChronometricAgeConversionProtocol' namespace='http://zooarchnet.org/dwc/terms/' qualName='http://zooarchnet.org/dwc/terms/verbatimChronometricAgeConversionProtocol' dc:description='The method used for converting the verbatimChronometricAge into a chronometric date in years, as captured in the maximumChronometricAge, maximumChronometricAgeReferenceSystem, minimumChronometricAge, and minimumChronometricAgeReferenceSystem fields. For example, calibration of conventional radiocarbon age or the currently accepted age range of a cultural or geological period.' examples='' type="string" required='false'/>
    <property name='maximumChronometricAge' namespace='http://zooarchnet.org/dwc/terms/' qualName='http://zooarchnet.org/dwc/terms/maximumChronometricAge' dc:description='Upper limit for the age of a specimen as determined by a dating method.' examples='27' type="integer" required='false'/>
    <property name='maximumChronometricAgeReferenceSystem' namespace='http://zooarchnet.org/dwc/terms/' qualName='http://zooarchnet.org/dwc/terms/maximumChronometricAgeReferenceSystem' dc:description='The reference system associated with the maximumChronometricAge. For example, BC. The unit for this field is years.' examples='"kya", "mya", "BP", "AD", "BCE"' type="string" required='false'/>
    <property name='minimumChronometricAge' namespace='http://zooarchnet.org/dwc/terms/' qualName='http://zooarchnet.org/dwc/terms/minimumChronometricAge' dc:description='Lower limit for the age of a specimen as determined by a dating method.' examples='14' type="integer" required='false'/>
    <property name='minimumChronometricAgeReferenceSystem' namespace='http://zooarchnet.org/dwc/terms/' qualName='http://zooarchnet.org/dwc/terms/minimumChronometricAgeReferenceSystem' dc:description='The reference system associated with the minimumChronometricAge. For example, AD. The unit for this field is years.' examples='"kya", "mya", "BP", "AD", "BCE"' type="string" required='false'/>
    <property name='chronometricAgeUncertaintyInYears' namespace='http://zooarchnet.org/dwc/terms/' qualName='http://zooarchnet.org/dwc/terms/chronometricAgeUncertaintyInYears' dc:description='The temporal uncertainty of the maximumAge and minimumAge, in years.' examples='100' type="integer" required='false'/>
    <property name='chronometricAgeUncertaintyMethod' namespace='http://zooarchnet.org/dwc/terms/' qualName='http://zooarchnet.org/dwc/terms/chronometricAgeUncertaintyMethod' dc:description='The method used to generate the reported uncertainty calculations.' examples='' type="string" required='false'/>
    <property name='materialDated' namespace='http://zooarchnet.org/dwc/terms/' qualName='http://zooarchnet.org/dwc/terms/materialDated' dc:description='A description of the material on which the chronometricDateProtocol was actually performed, if known.' examples='' type="string" required='false'/>
    <property name="materialDatedID" namespace="http://zooarchnet.org/dwc/terms/" qualName="http://zooarchnet.org/dwc/terms/materialDatedID" dc:description='An identifier for the material on which the chronometricDateProtocol was performed, if applicable.' examples='If the material dated is not the sample itself (or even to clarify if it is), an identifier can be given.' type="string" required="false"/>
    <property name='chronometricDateProtocol' namespace='http://zooarchnet.org/dwc/terms/' qualName='http://zooarchnet.org/dwc/terms/chronometricDateProtocol' dc:description='A description or reference to the methods used to determine the ChronometricDate.' examples='' type="string" required='false'/>
    <property name='chronometricDateReferences' namespace='http://zooarchnet.org/dwc/terms/' qualName='http://zooarchnet.org/dwc/terms/chronometricDateReferences' dc:description='A list (concatenated and separated) of identifiers (publication, bibliographic reference, global unique identifier, URI) of literature associated with the ChronometricDate.' examples='' type="string" required='false'/>
    <property name='chronometricDateRemarks' namespace='http://zooarchnet.org/dwc/terms/' qualName='http://zooarchnet.org/dwc/terms/chronometricDateRemarks' dc:description='Notes or comments about the ChronometricDate.' examples='' type="string" required='false'/>
</extension>
