=== gbif/rs.gbif.org/schema/extension.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dc="http://purl.org/dc/terms/" xmlns:ext="http://rs.gbif.org/extension/"
    targetNamespace="http://rs.gbif.org/extension/" elementFormDefault="qualified"
    attributeFormDefault="unqualified">
    <xs:import namespace="http://purl.org/dc/terms/" schemaLocation="dc.xsd"/>
    <xs:element name="extension">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="property" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:NCName" use="required">
                            <xs:annotation>
                                <xs:documentation>lowerCamelCase, whitespace less simple name for the property that can for example be used to generate XML tags or json attribute names</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="namespace" type="xs:anyURI" use="required">
                            <xs:annotation>
                                <xs:documentation>The namespace this extension belongs to</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="qualName" type="xs:anyURI" use="required">
                            <xs:annotation>
                                <xs:documentation>The fully qualified name combining the simple name with the namespace.</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="group" type="xs:string" use="optional">
                            <xs:annotation>
                                <xs:documentation>Optional group name to organise properties in extensions in case there are many</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="columnLength" type="xs:positiveInteger" default="128"/>
                        <xs:attribute name="type" type="ext:dataType" default="string" use="optional">
                            <xs:annotation>
                                <xs:documentation>The data type for the property. Defaults to a string.</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>

                        <xs:attribute name="examples" type="xs:string">
                            <xs:annotation>
                                <xs:documentation>Example content for the property. If multiple are given delimited by a semicolon</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute ref="dc:relation"/>
                        <xs:attribute ref="dc:subject" use="optional"/>
                        <xs:attribute ref="dc:description" use="optional"> </xs:attribute>
                        <xs:attribute name="thesaurus" type="xs:anyURI">
                            <xs:annotation>
                                <xs:documentation>A uri identifying a vocabulary to be used for property values</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="required" type="xs:boolean" default="false"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute ref="dc:title" use="required">
                <xs:annotation>
                    <xs:documentation>The human readable english title for the entire extension</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="name" type="xs:NCName" use="required">
                <xs:annotation>
                    <xs:documentation>Capital, whitespace less simple name for the extension that can for example be used to generate XML tags</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="namespace" type="xs:anyURI" use="required">
                <xs:annotation>
                    <xs:documentation>The namespace this extension belongs to</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="rowType" type="xs:anyURI" use="required">
                <xs:annotation>
                    <xs:documentation>The rowType is the qualified name when combined with the namespace. Double or missing slashes are removed/added when name + namespace is combined.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute ref="dc:issued" use="required">
                <xs:annotation>
                    <xs:documentation>The date that the extension (version) was officially released.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute ref="dc:description" use="optional"/>
            <xs:attribute ref="dc:relation" use="optional"/>
            <xs:attribute ref="dc:subject" use="optional"/>
        </xs:complexType>
    </xs:element>

    <!-- Enumeration of supported data types -->
    <xs:simpleType name="dataType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="string"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="decimal"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="uri"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== gbif/rs.gbif.org/extension/gbif/1.0/description.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<extension xmlns="http://rs.gbif.org/extension/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:dc="http://purl.org/dc/terms/"    
    xsi:schemaLocation="http://rs.gbif.org/extension/ http://rs.gbif.org/schema/extension.xsd"
    dc:title="Taxon Description" 
    name="Description" namespace="http://rs.gbif.org/terms/1.0" rowType="http://rs.gbif.org/terms/1.0/Description"
    dc:issued="2015-02-13"
    dc:relation=""
    dc:subject="dwc:Taxon checklist"
    dc:description="DwC Taxon extension to exchange simple text/paragraph based taxon descriptions. Not suitable for structured descriptions and keys, but useful for creating species pages.">

    <property name='description' namespace='http://purl.org/dc/terms/' qualName='http://purl.org/dc/terms/description' dc:relation='' dc:description='Any descriptive free text matching the category given as dc:type. The text should be either plain text or formatted with basic html tags, i.e. h1-4,p,i,b,a,img,ul and li. All other tags should be removed.' examples='' required='true'/>
    <property name='type' thesaurus="http://rs.gbif.org/vocabulary/gbif/description_type.xml"  namespace='http://purl.org/dc/terms/' qualName='http://purl.org/dc/terms/type' dc:relation='' dc:description='The kind of description given' examples='morphology, distribution' required='true'/>
    <property name='source' namespace='http://purl.org/dc/terms/' qualName='http://purl.org/dc/terms/source' dc:relation='' dc:description='Source reference of this description, a URL or full publication citation' examples='' required='false'/>
    <property name='language' namespace='http://purl.org/dc/terms/' qualName='http://purl.org/dc/terms/language' dc:relation='' dc:description='ISO 639-1 language code used for the vernacular name value.' examples='ES' required='false'/>
    <property name="created" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/created" dc:description='The date and time this description was written or last updated' examples='2010-09-29' type="date"/>
    <property name='creator' namespace='http://purl.org/dc/terms/' qualName='http://purl.org/dc/terms/creator' dc:relation='' dc:description='The author(s) of the textual information provided for a description' examples='' required='false'/>
    <property name='contributor' namespace='http://purl.org/dc/terms/' qualName='http://purl.org/dc/terms/contributor' dc:relation='' dc:description='An entity responsible for making contributions to the textual information provided for a description' examples='' required='false'/>
    <property name='audience' namespace='http://purl.org/dc/terms/' qualName='http://purl.org/dc/terms/audience' dc:relation='' dc:description='A class or description for whom the dwc:description is intended or useful' examples='"experts", "general public", "children"' required='false'/>
    <property name='license' namespace='http://purl.org/dc/terms/' qualName='http://purl.org/dc/terms/license' dc:relation='' dc:description='Official permission to do something with the resource. Please use Creative Commons URIs if you can.' examples='CC-BY' required='false'/>
    <property name='rightsHolder' namespace='http://purl.org/dc/terms/' qualName='http://purl.org/dc/terms/rightsHolder' dc:relation='' dc:description='A person or organization owning or managing rights over the description.' examples='' required='false'/>
    
</extension>

=== gbif/rs.gbif.org/extension/dwc/resource_relationship_2022-02-02.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='/style/human.xsl'?>
<extension xmlns='http://rs.gbif.org/extension/'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:dc='http://purl.org/dc/terms/'
    xsi:schemaLocation='http://rs.gbif.org/extension/ http://rs.gbif.org/schema/extension.xsd'
    dc:title='Darwin Core Resource Relationship'
    name='ResourceRelationship' namespace='http://rs.tdwg.org/dwc/terms/'
    rowType='http://rs.tdwg.org/dwc/terms/ResourceRelationship'
    dc:issued='2025-06-12'
    dc:subject='dwc:Occurrence dwc:Event dwc:Taxon'
    dc:relation='http://rs.tdwg.org/dwc/terms/ResourceRelationship'
    dc:description='Extended support for relationships between resources in a Darwin Core Occurrence, Event, or Taxon Core to resources in an extension or external to the data set. The identifiers for subject (resourceID) and object (relatedResourceID) may exist in the dataset or be accessible via an externally resolvable identifiers.'>

    <!-- ResourceRelationship -->
    <property group='ResourceRelationship' name='resourceRelationshipID' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/resourceRelationshipID' dc:relation='https://dwc.tdwg.org/terms/#dwc:resourceRelationshipID' dc:description='An identifier for an instance of relationship between one resource (the subject) and another (dwc:relatedResource, the object).' comments='' examples='`04b16710-b09c-11e8-96f8-529269fb1459`' required='false'/>
    <property group='ResourceRelationship' name='resourceID' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/resourceID' dc:relation='https://dwc.tdwg.org/terms/#dwc:resourceID' dc:description='An identifier for the resource that is the subject of the relationship.' comments='' examples='`f809b9e0-b09b-11e8-96f8-529269fb1459`' required='true'/>
    <property group='ResourceRelationship' name='relationshipOfResourceID' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/relationshipOfResourceID' dc:relation='https://dwc.tdwg.org/terms/#dwc:relationshipOfResourceID' dc:description='An identifier for the relationship type (predicate) that connects the subject identified by dwc:resourceID to its object identified by dwc:relatedResourceID.' comments='Recommended best practice is to use the identifiers of the terms in a controlled vocabulary, such as the OBO Relation Ontology.' examples='`http://purl.obolibrary.org/obo/RO_0002456` (for the relation `pollinated by`); `http://purl.obolibrary.org/obo/RO_0002455` (for the relation `pollinates`); `https://www.inaturalist.org/observation_fields/879` (for the relation `eaten by`)' required='false'/>
    <property group='ResourceRelationship' name='relatedResourceID' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/relatedResourceID' dc:relation='https://dwc.tdwg.org/terms/#dwc:relatedResourceID' dc:description='An identifier for a related resource (the object, rather than the subject of the relationship).' comments='' examples='`dc609808-b09b-11e8-96f8-529269fb1459`' required='true'/>
    <property group='ResourceRelationship' name='relationshipOfResource' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/relationshipOfResource' dc:relation='https://dwc.tdwg.org/terms/#dwc:relationshipOfResource' dc:description='The relationship of the subject (identified by dwc:resourceID) to the object (identified by dwc:relatedResourceID).' comments='Recommended best practice is to use a controlled vocabulary.' examples='`same as`; `duplicate of`; `mother of`; `offspring of`; `sibling of`; `parasite of`; `host of`; `valid synonym of`; `located within`; `pollinator of members of taxon`; `pollinated specific plant`; `pollinated by members of taxon`; `on slab with`' required='false'/>
    <property group='ResourceRelationship' name='relationshipAccordingTo' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/relationshipAccordingTo' dc:relation='https://dwc.tdwg.org/terms/#dwc:relationshipAccordingTo' dc:description='The source (person, organization, publication, reference) establishing the relationship between the two resources.' comments='' examples='`Julie Woodruff`' required='false'/>
    <property group='ResourceRelationship' name='relationshipEstablishedDate' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/relationshipEstablishedDate' dc:relation='https://dwc.tdwg.org/terms/#dwc:relationshipEstablishedDate' dc:description='The date-time on which the relationship between the two resources was established.' comments='Recommended best practice is to use a date that conforms to ISO 8601-1:2019.' examples='`1963-03-08T14:07-06:00` (8 Mar 1963 at or after 2:07pm and before 2:08pm in the time zone six hours earlier than UTC); `2009-02-20T08:40Z` (20 February 2009 at or after 8:40am and before 8:41 UTC); `2018-08-29T15:19` (29 August 2018 at or after 3:19pm and before 3:20pm local time); `1809-02-12` (within the day 12 February 1809); `1906-06` (in the month of June 1906); `1971` (in the year 1971); `2007-03-01T13:00:00Z/2008-05-11T15:30:00Z` (some time within the interval beginning 1 March 2007 at 1pm UTC and before 11 May 2008 at 3:30pm UTC); `1900/1909` (some time within the interval between the beginning of the year 1900 and before the year 1909); `2007-11-13/15` (some time in the interval between the beginning of 13 November 2007 and before 15 November 2007)' required='false'/>
    <property group='ResourceRelationship' name='relationshipRemarks' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/relationshipRemarks' dc:relation='https://dwc.tdwg.org/terms/#dwc:relationshipRemarks' dc:description='Comments or notes about the relationship between the two resources.' comments='' examples='`mother and offspring collected from the same nest`; `pollinator captured in the act`' required='false'/>
</extension>

=== gbif/rs.gbif.org/extension/dwc/resource_relation.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<extension xmlns="http://rs.gbif.org/extension/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:dc="http://purl.org/dc/terms/"    
    xsi:schemaLocation="http://rs.gbif.org/extension/ http://rs.gbif.org/schema/extension.xsd"
    dc:title="Darwin Core Resource Relationship" 
    name="ResourceRelationship" namespace="http://rs.tdwg.org/dwc/terms/" rowType="http://rs.tdwg.org/dwc/terms/ResourceRelationship"
    dc:issued="2015-02-13"
    dc:subject=""
    dc:relation="http://rs.tdwg.org/dwc/terms/index.htm#relindex"
    dc:description="Support for generic resource rleations according to Darwin Core terms.">

    <property name='resourceRelationshipID' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/resourceRelationshipID' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#resourceRelationshipID' dc:description='An identifier for an instance of relationship between one resource (the subject) and another (relatedResource, the object).' examples='' required='false'/>
    <property name='relatedResourceID' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/relatedResourceID' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#relatedResourceID' dc:description='An identifier for a related resource (the object, rather than the subject of the relationship).' examples='' required='false'/>
    <property name='relationshipOfResource' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/relationshipOfResource' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#relationshipOfResource' dc:description='The relationship of the resource identified by relatedResourceID to the subject (optionally identified by the resourceID). Recommended best practice is to use a controlled vocabulary.' examples='duplicate of", "mother of", "endoparasite of", "host to", "sibling of", "valid synonym of", "located within"' required='false'/>
    <property name='relationshipAccordingTo' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/relationshipAccordingTo' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#relationshipAccordingTo' dc:description='The source (person, organization, publication, reference) establishing the relationship between the two resources.' examples='Julie Woodruff' required='false'/>
    <property name='relationshipEstablishedDate' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/relationshipEstablishedDate' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#relationshipEstablishedDate' dc:description='The date-time on which the relationship between the two resources was established. Recommended best practice is to use an encoding scheme, such as ISO 8601:2004(E).' examples='1963-03-08T14:07-0600' required='false'/>
    <property name='relationshipRemarks' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/relationshipRemarks' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#relationshipRemarks' dc:description='Comments or notes about the relationship between the two resources.' examples='mother and offspring collected from the same nest' required='false'/>
    <property name='scientificName' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/scientificName' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#scientificName' dc:description='A taxon name that is the object (relatedResource) of an association with the subject (either a taxon or a taxon occurrence)' examples='Quercus agrifolia var. oxyadenia (Torr.)' required='false'/>
    
</extension>

=== gbif/rs.gbif.org/sandbox/extension/gbif/1.0/typesandspecimen_2026-03-09.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<extension xmlns="http://rs.gbif.org/extension/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:dc="http://purl.org/dc/terms/"    
    xsi:schemaLocation="http://rs.gbif.org/extension/ http://rs.gbif.org/schema/extension.xsd"
    rowType="http://rs.gbif.org/terms/1.0/TypesAndSpecimen"
    dc:issued="2026-03-09"
    dc:title="Types and Specimen" name="TypesAndSpecimen" namespace="http://rs.gbif.org/terms/1.0"
    dc:subject="dwc:Taxon"
    dc:relation="http://rs.gbif.org/extension/gbif/1.0/typesandspecimen.xml"
    dc:description="An extension for specimens and types, including type specimens, type species and type genera and simple specimens unrelated to types.">
    
    <property name='typeStatus' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/typeStatus' thesaurus="http://rs.gbif.org/vocabulary/gbif/type_status.xml" dc:relation='' dc:description='The type status of the specimen, not used for type species or type genus' examples='holotype, syntype, lectotype, type species' required='false'/>
    <property name='typeDesignationType' namespace='http://rs.gbif.org/terms/1.0/' qualName='http://rs.gbif.org/terms/1.0/typeDesignationType' thesaurus="http://rs.gbif.org/vocabulary/gbif/type_designation_type.xml" dc:relation='' dc:description='The reason why this specimen or name is designated as a type.' examples='monotypy, original designation, tautonomy' required='false'/>
    <property name='typeDesignatedBy' namespace='http://rs.gbif.org/terms/1.0/' qualName='http://rs.gbif.org/terms/1.0/typeDesignatedBy' dc:relation='' dc:description='The citation of the publication where the type designation is found' examples='Vachal, J. (1897) Éclaircissements sur de genre Scrapter et description d’une espéce nouvelle de Dufourea. Bulletin de la Société Entomologique de France, 1897, 61–64.' required='false'/>
    <property name='scientificName' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/scientificName' dc:relation='' dc:description='In case of type specimens the scientific name originally used on the label. Not necessarily the same as the currently recognized name. In case of type species or genera it should be the species or genus name that typifies the higher taxon.' examples='Ctenomys sociabilis" "Roptrocerus typographi (Györfi, 1952)" ' required='false'/>
    <property name='taxonRank' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/taxonRank' dc:relation='' dc:description='The rank of the taxon bearing the scientific name' examples='species, genus, subspecies' required='false'/>
    <property name='bibliographicCitation' namespace='http://purl.org/dc/terms/' qualName='http://purl.org/dc/terms/bibliographicCitation' dc:relation='' dc:description='A text string citating the described specimen. Often found in taxonomic treatments and frequently based on institution code and catalog number.' examples='Iraq: Mosul: Jabal Khantur prope Sharanish N. Zakho, in fissures rupium calc., 1200 m, Rech. 12083 (W!).' required='false'/>
    <property name='occurrenceID' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/occurrenceID' dc:relation='' dc:description='An identifier for the specimen, preferably a resolvable globally unique identifier.' examples='' required='false'/>
    <property name='institutionCode' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/institutionCode' dc:relation='' dc:description='The name (or acronym) in use by the institution having custody of the object(s) or information referred to in the record.' examples='"MVZ", "FMNH", "AKN-CLO", "University of California Museum of Paleontology (UCMP)"' required='false'/>
    <property name='institutionID' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/institutionID' dc:relation='' dc:description='An identifier for the institution having custody of the object(s) or information referred to in the record.' examples='"https://ror.org/015hz7p22", "http://grscicoll.org/institution/museum-southwestern-biology", "https://www.gbif.org/grscicoll/institution/e3d4dcc4-81e2-444c-8a5c-41d1044b5381"' required='false'/>
    <property name='collectionCode' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/collectionCode' dc:relation='' dc:description='The name, acronym, coden, or initialism identifying the collection or data set from which the record was derived.' examples='"Mammals", "Hildebrandt", "eBird"' required='false'/>
    <property name='collectionID' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/collectionID' dc:relation='' dc:description='An identifier for the collection or dataset from which the record was derived.' examples='"https://scientific-collections.gbif.org/collection/fbd3ed74-5a21-4e01-b86a-33d36f032d9c"' required='false'/>    
    <property name='catalogNumber' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/catalogNumber' dc:relation='' dc:description='An identifier (preferably unique) for the record within the data set or collection.' examples='"2008.1334", "145732a", "145732"' required='false'/>
    <property name='locality' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/locality' dc:relation='' dc:description='The location where the the specimen was collected. In case of type specimens the type locality.' examples='Iraq: Mosul: Jabal Khantur prope Sharanish N. Zakho, in fissures rupium calc., 1200 m' required='false'/>
    <property name='sex' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/sex' dc:relation='' dc:description='The sex of the specimen being referenced.' examples='male' required='false'/>
    <property name='recordedBy' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/recordedBy' dc:relation='' dc:description='The primary collector or observer, especially one who applies a personal identifier (recordNumber), should be listed first.' examples='KH Rechinger' required='false'/>
    <property name='source' namespace='http://purl.org/dc/terms/' qualName='http://purl.org/dc/terms/source' dc:relation='' dc:description='' examples='' required='false'/>
    <property name='verbatimEventDate' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/verbatimEventDate' dc:relation='' dc:description='The date when the specimen was collected' examples='"spring 1910", "Marzo 2002", "1999-03-XX", "17IV1934"' required='false'/>
    <property name='verbatimLabel' namespace='http://rs.gbif.org/terms/1.0/' qualName='http://rs.gbif.org/terms/1.0/verbatimLabel' dc:relation='' dc:description='The full, verbatim text from the specimen label' examples='' required='false'/>
    <property name='verbatimLongitude' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/verbatimLongitude' dc:relation='' dc:description='The geographic longitude ' examples="121d 10' 34 W" required='false'/>
    <property name='verbatimLatitude' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/verbatimLatitude' dc:relation='' dc:description='The geographic latitude ' examples='41 05 54.03S' required='false'/>
    <property name='datasetID' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/datasetID' dc:relation='http://rs.tdwg.org/dwc/terms/index.htm#datasetID' dc:description='An identifier for a subset of data.' examples='' required='false'/>
    
</extension>
