=== gbif/rs.gbif.org/schema/thesaurus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://rs.gbif.org/thesaurus/"
	xmlns:dc="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/"
	xmlns:xml="http://www.w3.org/XML/1998/namespace" targetNamespace="http://rs.gbif.org/thesaurus/"
	elementFormDefault="qualified">
	<xs:import namespace="http://purl.org/dc/terms/" schemaLocation="dc.xsd"/>
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"
		schemaLocation="http://rs.gbif.org/schema/xml.xsd"/>
	<xs:element name="thesaurus">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="concept" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute ref="dc:URI" use="required"/>
			<xs:attribute ref="dc:title" use="required"/>
			<xs:attribute ref="dc:issued" use="required">
				<xs:annotation>
					<xs:documentation>The date that the vocabulary (version) was officially released.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:description" use="optional"/>
			<xs:attribute ref="dc:relation" use="optional"/>
			<xs:attribute ref="dc:subject" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="concept">
		<xs:complexType>

			<xs:sequence>
				<!-- Many titles per language for synonyms -->
				<xs:element name="preferred">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="term" maxOccurs="unbounded" minOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<!-- Many titles per language for synonyms -->
				<xs:element name="alternative" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="term" maxOccurs="unbounded" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute ref="dc:URI" use="required">
				<xs:annotation>
					<xs:documentation>The proper full URI. Preferably pointing to an
						RDF document in an ontology</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:description" use="optional"/>
			<xs:attribute ref="dc:relation" use="optional"/>
			<xs:attribute name="comments" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Recommendations for the content for the property.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:subject" use="optional"/>
			<xs:attribute ref="dc:identifier" use="required">
				<xs:annotation>
					<xs:documentation>A short code locally unique within a vocabulary
						as identified by the dc:type attribute.
						Should be language neutral as much as possible. E.g. DE for Germany or
						familia for the family rank</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:issued" use="optional"/>
			<xs:anyAttribute processContents="lax"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="term">
		<xs:complexType>
			<xs:attribute ref="dc:title" use="required">
				<xs:annotation>
					<xs:documentation>The term itself</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="xml:lang" use="optional">
				<xs:annotation>
					<xs:documentation>ISO 2 letter language code only!</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:source" use="optional">
				<xs:annotation>
					<xs:documentation>The source where the term originated from
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:modified" use="optional"/>
			<xs:anyAttribute processContents="lax"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gbif/rs.gbif.org/vocabulary/gbif/vegetation_layer.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus 
    dc:URI="http://rs.gbif.org/vocabulary/gbif/vegetationLayer" 
    dc:description="A vocabulary representing vegetation layers, including aquatic vegetation layers, and their sub-layers." 
    dc:title="Vegetation Layer GBIF Vocabulary"
    dc:issued="2016-04-05"
    xmlns="http://rs.gbif.org/thesaurus/" xmlns:dc="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">
	
    <concept dc:identifier="tree" dc:URI="http://rs.gbif.org/vocabulary/gbif/vegetationLayer/tree" 
        dc:relation=""
        dc:description="Includes all woody plants greater than five meters tall.">
        <preferred>
            <term dc:title="Tree layer" xml:lang="en"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="emergent" dc:URI="http://rs.gbif.org/vocabulary/gbif/vegetationLayer/emergent" 
        dc:relation=""
        dc:description="The tree layer above the general canopy.">
        <preferred>
            <term dc:title="Emergent layer" xml:lang="en"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="canopy" dc:URI="http://rs.gbif.org/vocabulary/gbif/vegetationLayer/canopy" 
        dc:relation=""
        dc:description="The upper tree layer, made up of the crowns of its tallest trees.">
        <preferred>
            <term dc:title="Canopy layer" xml:lang="en"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="understory" dc:URI="http://rs.gbif.org/vocabulary/gbif/vegetationLayer/understory" 
        dc:relation=""
        dc:description="The lower tree layer, made up of trees above the shrub layer and below the canopy.">
        <preferred>
            <term dc:title="Understory layer" xml:lang="en"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="shrub" dc:URI="http://rs.gbif.org/vocabulary/gbif/vegetationLayer/shrub" 
        dc:relation=""
        dc:description="Includes all woody plants between one and a half and five meters tall, except low woody or trailing plants which are considered part of the herb layer.">
        <preferred>
            <term dc:title="Shrub layer" xml:lang="en"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="juvenile" dc:URI="http://rs.gbif.org/vocabulary/gbif/vegetationLayer/juvenile" 
        dc:relation=""
        dc:description="The shrub layer, made up of all juvenile trees.">
        <preferred>
            <term dc:title="Juvenile layer" xml:lang="en"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="herbaceous" dc:URI="http://rs.gbif.org/vocabulary/gbif/vegetationLayer/herbaceous" 
        dc:relation=""
        dc:description="Includes all herbaceous (non woody) species, regardless of height, and some low woody plants up to one and a half meters tall.">
        <preferred>
            <term dc:title="Herbaceous layer" xml:lang="en"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="seedling" dc:URI="http://rs.gbif.org/vocabulary/gbif/vegetationLayer/seedling" 
        dc:relation=""
        dc:description="The herbaceous layer, made up of all tree seedlings.">
        <preferred>
            <term dc:title="Seedling layer" xml:lang="en"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="cryptogam" dc:URI="http://rs.gbif.org/vocabulary/gbif/vegetationLayer/cryptogam" 
        dc:relation=""
        dc:description="Includes all cryptogams.">
        <preferred>
            <term dc:title="Cryptogam layer" xml:lang="en"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="rhizosphere" dc:URI="http://rs.gbif.org/vocabulary/gbif/vegetationLayer/rhizosphere" 
        dc:relation=""
        dc:description="The root layer, made up of the underground area of a plant habitat.">
        <preferred>
            <term dc:title="Rhizosphere layer" xml:lang="en"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>    
    <concept dc:identifier="submerged" dc:URI="http://rs.gbif.org/vocabulary/gbif/vegetationLayer/submerged" 
        dc:relation=""
        dc:description="The submerged layer in the littoral zone, made up of sediment-rooted macrophytes.">
        <preferred>
            <term dc:title="Submerged layer" xml:lang="en"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="emergentAquatic" dc:URI="http://rs.gbif.org/vocabulary/gbif/vegetationLayer/emergentAquatic" 
        dc:relation=""
        dc:description="The partly-submerged layer in the littoral zone, made up of sediment-rooted macrophytes.">
        <preferred>
            <term dc:title="Emergent (aquatic) layer" xml:lang="en"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="floating" dc:URI="http://rs.gbif.org/vocabulary/gbif/vegetationLayer/floating" 
        dc:relation=""
        dc:description="The floating layer in the littoral zone, made up of sediment-rooted macrophytes. E.g. Nymphaea.">
        <preferred>
            <term dc:title="Floating layer" xml:lang="en"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="freeFloating" dc:URI="http://rs.gbif.org/vocabulary/gbif/vegetationLayer/freeFloating" 
        dc:relation=""
        dc:description="The free-floating layer in the littoral zone, made up of non-sediment-rooted macrophytes. E.g. Lemna.">
        <preferred>
            <term dc:title="Free-Floating layer" xml:lang="en"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>    
</thesaurus>

=== gbif/rs.gbif.org/sandbox/vocabulary/mixs/bin_software.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/bin_software/'
    dc:description="The binning software Vocabulary is a recommended set of values to use for the bin_software term in the MIxS Extension."
    dc:title="Genomic Standards Consortium binning software Vocabulary"
    dc:issued="2020-04-24"
    dc:relation=""
    xmlns="http://rs.gbif.org/thesaurus/"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">
    <concept dc:identifier="metabat"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/bin_software/metabat'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="metabat"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="maxbin"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/bin_software/maxbin'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="maxbin"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="concoct"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/bin_software/concoct'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="concoct"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="groupm"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/bin_software/groupm'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="groupm"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="esom"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/bin_software/esom'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="esom"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="metawatt"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/bin_software/metawatt'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="metawatt"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="combination"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/bin_software/combination'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="combination"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="other"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/bin_software/other'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="other"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
</thesaurus>

=== gbif/rs.gbif.org/vocabulary/eol/mimetype.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus 
    dc:URI="http://www.eol.org/IPT/vocabulary/mimetype" 
	dc:description="MIME type for EOL data objects" 
	dc:title="MIME Type EOL Vocabulary" 
	xmlns="http://rs.gbif.org/thesaurus/" xmlns:dc="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">	

    <concept dc:identifier="audio/mpeg" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/audio/mpeg" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="audio/mpeg" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="audio/x-ms-wma" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/audio/x-ms-wma" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="audio/x-ms-wma" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="audio/x-pn-realaudio" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/audio/x-pn-realaudio" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="audio/x-pn-realaudio" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="audio/x-realaudio" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/audio/x-realaudio" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="audio/x-realaudio" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="audio/x-wav" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/audio/x-wav" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="audio/x-wav" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="image/bmp" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/image/bmp" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="image/bmp" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="image/gif" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/image/gif" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="image/gif" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="image/jpeg" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/image/jpeg" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="image/jpeg" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="image/png" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/image/png" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="image/png" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="image/svg+xml" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/image/svgxml" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="image/svg+xml" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="image/tiff" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/image/tiff" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="image/tiff" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="text/html" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/text/html" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="text/html" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="text/plain" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/text/plain" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="text/plain" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="text/richtext" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/text/richtext" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="text/richtext" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="text/rtf" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/text/rtf" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="text/rtf" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="text/xml" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/text/xml" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="text/xml" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="video/mp4" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/video/mp4" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="video/mp4" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="video/mpeg" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/video/mpeg" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="video/mpeg" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="video/quicktime" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/video/quicktime" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="video/quicktime" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="video/x-flv" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/video/x-flv" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="video/x-flv" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="video/x-ms-wmv" dc:URI="http://www.eol.org/IPT/vocabulary/mimetype/video/x-ms-wmv" dc:relation="" dc:description="">
      <preferred>
        <term dc:title="video/x-ms-wmv" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

</thesaurus>

=== gbif/rs.gbif.org/sandbox/vocabulary/mixs/pred_genome_struc.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/pred_genome_struc/'
  dc:description="The predicted genome structure Vocabulary is a recommended set of values to use for the pred_genome_struc term in the MIxS Extension."
  dc:title="Genomic Standards Consortium predicted genome structure Vocabulary"
  dc:issued="2020-04-24"
  dc:relation=""
  xmlns="http://rs.gbif.org/thesaurus/"
  xmlns:dc="http://purl.org/dc/terms/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">
  <concept dc:identifier="segmented"
    dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/pred_genome_struc/segmented'
    dc:description="">
    <preferred>
      <term dc:source="Genomic Standards Consortium MIxS Data Standard"
        dc:title="segmented"
        xml:lang="en"/>
    </preferred>
    <alternative></alternative>
  </concept>
  <concept dc:identifier="non-segmented"
    dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/pred_genome_struc/non-segmented'
    dc:description="">
    <preferred>
      <term dc:source="Genomic Standards Consortium MIxS Data Standard"
        dc:title="non-segmented"
        xml:lang="en"/>
    </preferred>
    <alternative></alternative>
  </concept>
  <concept dc:identifier="undetermined"
    dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/pred_genome_struc/undetermined'
    dc:description="">
    <preferred>
      <term dc:source="Genomic Standards Consortium MIxS Data Standard"
        dc:title="undetermined"
        xml:lang="en"/>
    </preferred>
    <alternative></alternative>
  </concept>
</thesaurus>

=== gbif/rs.gbif.org/sandbox/vocabulary/mixs/host_pred_appr.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/host_pred_appr/'
    dc:description="The host prediction approach Vocabulary is a recommended set of values to use for the host_pred_appr term in the MIxS Extension."
    dc:title="Genomic Standards Consortium host prediction approach Vocabulary"
    dc:issued="2020-04-24"
    dc:relation=""
    xmlns="http://rs.gbif.org/thesaurus/"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">
    <concept dc:identifier="provirus"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/host_pred_appr/provirus'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="provirus"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="host_sequence_similarity"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/host_pred_appr/host_sequence_similarity'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="host sequence similarity"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="crispr_spacer_match"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/host_pred_appr/crispr_spacer_match'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="CRISPR spacer match"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="kmer_similarity"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/host_pred_appr/kmer_similarity'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="kmer similarity"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="co-occurrence"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/host_pred_appr/co-occurrence'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="co-occurrence"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="combination"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/host_pred_appr/combination'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="combination"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="other"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/host_pred_appr/other'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="other"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
</thesaurus>

=== gbif/rs.gbif.org/sandbox/vocabulary/mixs/mag_cov_software.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/mag_cov_software/'
    dc:description="The MAG coverage software Vocabulary is a recommended set of values to use for the mag_cov_software term in the MIxS Extension."
    dc:title="Genomic Standards Consortium MAG coverage software Vocabulary"
    dc:issued="2020-04-24"
    dc:relation=""
    xmlns="http://rs.gbif.org/thesaurus/"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">
    <concept dc:identifier="bwa"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/mag_cov_software/bwa'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="bwa"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="bbmap"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/mag_cov_software/bbmap'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="bbmap"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="bowtie"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/mag_cov_software/bowtie'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="bowtie"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="other"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/mag_cov_software/other'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="other"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
</thesaurus>
