=== gbif/rs.gbif.org/schema/thesaurus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://rs.gbif.org/thesaurus/"
	xmlns:dc="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/"
	xmlns:xml="http://www.w3.org/XML/1998/namespace" targetNamespace="http://rs.gbif.org/thesaurus/"
	elementFormDefault="qualified">
	<xs:import namespace="http://purl.org/dc/terms/" schemaLocation="dc.xsd"/>
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"
		schemaLocation="http://rs.gbif.org/schema/xml.xsd"/>
	<xs:element name="thesaurus">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="concept" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute ref="dc:URI" use="required"/>
			<xs:attribute ref="dc:title" use="required"/>
			<xs:attribute ref="dc:issued" use="required">
				<xs:annotation>
					<xs:documentation>The date that the vocabulary (version) was officially released.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:description" use="optional"/>
			<xs:attribute ref="dc:relation" use="optional"/>
			<xs:attribute ref="dc:subject" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="concept">
		<xs:complexType>

			<xs:sequence>
				<!-- Many titles per language for synonyms -->
				<xs:element name="preferred">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="term" maxOccurs="unbounded" minOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<!-- Many titles per language for synonyms -->
				<xs:element name="alternative" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="term" maxOccurs="unbounded" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute ref="dc:URI" use="required">
				<xs:annotation>
					<xs:documentation>The proper full URI. Preferably pointing to an
						RDF document in an ontology</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:description" use="optional"/>
			<xs:attribute ref="dc:relation" use="optional"/>
			<xs:attribute name="comments" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Recommendations for the content for the property.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:subject" use="optional"/>
			<xs:attribute ref="dc:identifier" use="required">
				<xs:annotation>
					<xs:documentation>A short code locally unique within a vocabulary
						as identified by the dc:type attribute.
						Should be language neutral as much as possible. E.g. DE for Germany or
						familia for the family rank</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:issued" use="optional"/>
			<xs:anyAttribute processContents="lax"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="term">
		<xs:complexType>
			<xs:attribute ref="dc:title" use="required">
				<xs:annotation>
					<xs:documentation>The term itself</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="xml:lang" use="optional">
				<xs:annotation>
					<xs:documentation>ISO 2 letter language code only!</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:source" use="optional">
				<xs:annotation>
					<xs:documentation>The source where the term originated from
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:modified" use="optional"/>
			<xs:anyAttribute processContents="lax"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gbif/rs.gbif.org/sandbox/vocabulary/mixs/bin_param.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/bin_param/'
    dc:description="The binning parameters Vocabulary is a recommended set of values to use for the bin_param term in the MIxS Extension."
    dc:title="Genomic Standards Consortium binning parameters Vocabulary"
    dc:issued="2020-04-24"
    dc:relation=""
    xmlns="http://rs.gbif.org/thesaurus/"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">
    <concept dc:identifier="homology_search"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/bin_param/homology_search'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="homology search"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="kmer"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/bin_param/kmer'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="kmer"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="coverage"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/bin_param/coverage'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="coverage"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="codon_usage"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/bin_param/codon_usage'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="codon usage"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="combination"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/bin_param/combination'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="combination"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
</thesaurus>

=== gbif/rs.gbif.org/sandbox/vocabulary/mixs/lib_layout.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/lib_layout/'
    dc:description="The library layout Vocabulary is a recommended set of values to use for the lib_layout term in the MIxS Extension."
    dc:title="Genomic Standards Consortium library layout Vocabulary"
    dc:issued="2020-04-24"
    dc:relation=""
    xmlns="http://rs.gbif.org/thesaurus/"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">
    <concept dc:identifier="paired"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/lib_layout/paired'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="paired"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="single"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/lib_layout/single'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="single"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="vector"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/lib_layout/vector'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="vector"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="other"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/lib_layout/other'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="other"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
</thesaurus>

=== gbif/rs.gbif.org/vocabulary/gbif/occurrence_status.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus 
    dc:URI="http://rs.gbif.org/vocabulary/gbif/occurrence_status/" 
	dc:description="http://spreadsheets.google.com/pub?key=tVs-UWMXnkD3slwIE8T336w&amp;gid=3" 
	dc:title="Occurrence Status GBIF Vocabulary"
	dc:issued="2009-10-02"
  xmlns="http://rs.gbif.org/thesaurus/" xmlns:dc="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">
	
 <concept dc:identifier="present" dc:URI="http://rs.gbif.org/vocabulary/gbif/occurrence_status/present"  dc:issued="2009-10-02" dc:description="http://spreadsheets.google.com/pub?key=tVs-UWMXnkD3slwIE8T336w&amp;gid=3">
  <preferred>
   <term dc:source="" dc:title="present" xml:lang="en"/>
  </preferred>
  <alternative>
   <term dc:source="" dc:title="endemic" xml:lang="en"  />
   <term dc:source="" dc:title="native" xml:lang="en"  />
   <term dc:source="" dc:title="extant" xml:lang="en"  />
  </alternative>
 </concept>

 <concept dc:identifier="common" dc:URI="http://rs.gbif.org/vocabulary/gbif/occurrence_status/common"  dc:issued="2009-10-02" dc:description="http://spreadsheets.google.com/pub?key=tVs-UWMXnkD3slwIE8T336w&amp;gid=3">
  <preferred>
   <term dc:source="" dc:title="common" xml:lang="en"/>
  </preferred>
  <alternative>
   <term dc:source="" dc:title="frequent" xml:lang="en"  />
   <term dc:source="" dc:title="fairly common" xml:lang="en"  />
  </alternative>
 </concept>

 <concept dc:identifier="rare" dc:URI="http://rs.gbif.org/vocabulary/gbif/occurrence_status/rare"  dc:issued="2009-10-02" dc:description="http://spreadsheets.google.com/pub?key=tVs-UWMXnkD3slwIE8T336w&amp;gid=3">
  <preferred>
   <term dc:source="" dc:title="rare" xml:lang="en"/>
  </preferred>
  <alternative>
   <term dc:source="" dc:title="uncommon" xml:lang="en"  />
   <term dc:source="" dc:title="casual" xml:lang="en"  />
  </alternative>
 </concept>

 <concept dc:identifier="irregular" dc:URI="http://rs.gbif.org/vocabulary/gbif/occurrence_status/irregular"  dc:issued="2009-10-02" dc:description="http://spreadsheets.google.com/pub?key=tVs-UWMXnkD3slwIE8T336w&amp;gid=3">
  <preferred>
   <term dc:source="" dc:title="irregular" xml:lang="en"/>
  </preferred>
  <alternative>
   <term dc:source="" dc:title="ephemeral" xml:lang="en"  />
   <term dc:source="" dc:title="episodic" xml:lang="en"  />
   <term dc:source="" dc:title="vagrant" xml:lang="en"  />
  </alternative>
 </concept>

 <concept dc:identifier="doubtful" dc:URI="http://rs.gbif.org/vocabulary/gbif/occurrence_status/doubtful"  dc:issued="2009-10-02" dc:description="http://spreadsheets.google.com/pub?key=tVs-UWMXnkD3slwIE8T336w&amp;gid=3">
  <preferred>
   <term dc:source="" dc:title="doubtful" xml:lang="en"/>
  </preferred>
  <alternative>
   <term dc:source="" dc:title="possibly extant" xml:lang="en"  />
   <term dc:source="" dc:title="probably extant" xml:lang="en"  />
   <term dc:source="" dc:title="possibly extinct" xml:lang="en"  />
   <term dc:source="" dc:title="presence uncertain" xml:lang="en"  />
  </alternative>
 </concept>

 <concept dc:identifier="absent" dc:URI="http://rs.gbif.org/vocabulary/gbif/occurrence_status/absent"  dc:issued="2009-10-02" dc:description="http://spreadsheets.google.com/pub?key=tVs-UWMXnkD3slwIE8T336w&amp;gid=3">
  <preferred>
   <term dc:source="" dc:title="absent" xml:lang="en"/>
  </preferred>
  <alternative>
   <term dc:source="" dc:title="extinct" xml:lang="en"  />
   <term dc:source="" dc:title="extirpated" xml:lang="en"  />
  </alternative>
 </concept>

 <concept dc:identifier="excluded" dc:URI="http://rs.gbif.org/vocabulary/gbif/occurrence_status/excluded"  dc:issued="2009-10-02" dc:description="http://spreadsheets.google.com/pub?key=tVs-UWMXnkD3slwIE8T336w&amp;gid=3">
  <preferred>
   <term dc:source="" dc:title="excluded" xml:lang="en"/>
  </preferred>
  <alternative>
   <term dc:source="" dc:title="misidentification" xml:lang="en"  />
   <term dc:source="" dc:title="reported in error" xml:lang="en"  />
   <term dc:source="" dc:title="erroneous" xml:lang="en"  />
  </alternative>
 </concept>
</thesaurus>

=== gbif/rs.gbif.org/vocabulary/gbif/taxonomic_status_2022-02-02.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus
  dc:URI="http://rs.gbif.org/vocabulary/gbif/taxonomicStatus/"
  dc:description="Simple vocabulary to describe the taxonomic status of a name"
  dc:title="Taxonomic Status GBIF Vocabulary"
  dc:issued="2022-02-02"
  xmlns="http://rs.gbif.org/thesaurus/" xmlns:dc="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">

 <concept dc:identifier="accepted" dc:URI="http://rs.gbif.org/vocabulary/gbif/taxonomicStatus/accepted"
  dc:relation="http://rs.gbif.org/vocabulary/gbif/taxonomicStatus/accepted"
  dc:description="The status of a taxon according to the taxonomic judgement of a cited authority">
  <preferred>
   <term dc:title="accepted" xml:lang="en" />
  </preferred>
  <alternative>
   <term dc:title="valid" xml:lang="en" />
   <term dc:title="valid name" xml:lang="en" />
   <term dc:title="accepted name" xml:lang="en" />
  </alternative>
 </concept>

 <concept dc:identifier="doubtful" dc:URI="http://rs.gbif.org/vocabulary/gbif/taxonomicStatus/doubtful"
  dc:relation="http://rs.gbif.org/vocabulary/gbif/taxonomicStatus/doubtful"
  dc:description="Treated as accepted, but it is doubtful whether this is correct">
  <preferred>
   <term dc:title="doubtful" xml:lang="en" />
  </preferred>
 </concept>

 <concept dc:identifier="synonym" dc:URI="http://rs.gbif.org/vocabulary/gbif/taxonomicStatus/synonym"
  dc:relation="http://rs.gbif.org/vocabulary/gbif/taxonomicStatus/synonym"
  dc:description="if unclear whether hetero- or homotypic.  May be qualified by the nomenclatural status of the name">
  <preferred>
   <term dc:title="synonym" xml:lang="en" />
  </preferred>
  <alternative>
   <term dc:title="junior synonym" xml:lang="en" />
   <term dc:title="later synonym" xml:lang="en" />
   <term dc:title="unaccepted" xml:lang="en" />
   <term dc:title="unaccepted name" xml:lang="en" />
   <term dc:title="invalid" xml:lang="en" />
   <term dc:title="invalid name" xml:lang="en" />
  </alternative>
 </concept>

 <concept dc:identifier="heterotypicSynonym" dc:URI="http://rs.gbif.org/vocabulary/gbif/taxonomicStatus/heterotypicSynonym"
  dc:relation="http://rs.gbif.org/vocabulary/gbif/taxonomicStatus/heterotypicSynonym"
  dc:description="Subjective synonym based on different type(s)">
  <preferred>
   <term dc:title="heterotypicSynonym" xml:lang="en" />
  </preferred>
  <alternative>
   <term dc:title="subjective synonym" xml:lang="en" />
   <term dc:title="facultative synonym" xml:lang="en" />
   <term dc:title="taxonomic synonym" xml:lang="en" />
  </alternative>
 </concept>

 <concept dc:identifier="homotypicSynonym" dc:URI="http://rs.gbif.org/vocabulary/gbif/taxonomicStatus/homotypicSynonym"
  dc:relation="http://rs.gbif.org/vocabulary/gbif/taxonomicStatus/homotypicSynonym"
  dc:description="Objective synonym based on the same type(s)">
  <preferred>
   <term dc:title="homotypicSynonym" xml:lang="en" />
  </preferred>
  <alternative>
   <term dc:title="objective synonym" xml:lang="en" />
   <term dc:title="nomenclatural synonym" xml:lang="en" />
   <term dc:title="absolute synonym" xml:lang="en" />
  </alternative>
 </concept>

 <concept dc:identifier="proParteSynonym" dc:URI="http://rs.gbif.org/vocabulary/gbif/taxonomicStatus/proParteSynonym"
  dc:relation="http://rs.gbif.org/vocabulary/gbif/taxonomicStatus/proParteSynonym"
  dc:description="Some specimens of the original type series have been assigned to a new type">
  <preferred>
   <term dc:title="proParteSynonym" xml:lang="en" />
  </preferred>
  <alternative>
   <term dc:title="pro parte" xml:lang="en" />
  </alternative>
 </concept>

 <concept dc:identifier="misapplied" dc:URI="http://rs.gbif.org/vocabulary/gbif/taxonomicStatus/misapplied"
  dc:relation="http://rs.gbif.org/vocabulary/gbif/taxonomicStatus/misapplied"
  dc:description="">
  <preferred>
   <term dc:title="misapplied" xml:lang="en" />
  </preferred>
  <alternative>
   <term dc:title="misapplied name" xml:lang="en" />
  </alternative>
 </concept>

</thesaurus>

=== gbif/rs.gbif.org/sandbox/vocabulary/mixs/compl_appr.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/compl_appr/'
  dc:description="The completeness approach Vocabulary is a recommended set of values to use for the compl_appr term in the MIxS Extension."
  dc:title="Genomic Standards Consortium completeness approach Vocabulary"
  dc:issued="2020-04-24"
  dc:relation=""
  xmlns="http://rs.gbif.org/thesaurus/"
  xmlns:dc="http://purl.org/dc/terms/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">
  <concept dc:identifier="marker_gene"
    dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/compl_appr/marker_gene'
    dc:description="">
    <preferred>
      <term dc:source="Genomic Standards Consortium MIxS Data Standard"
        dc:title="marker gene"
        xml:lang="en"/>
    </preferred>
    <alternative></alternative>
  </concept>
  <concept dc:identifier="reference_based"
    dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/compl_appr/reference_based'
    dc:description="">
    <preferred>
      <term dc:source="Genomic Standards Consortium MIxS Data Standard"
        dc:title="reference based"
        xml:lang="en"/>
    </preferred>
    <alternative></alternative>
  </concept>
  <concept dc:identifier="other"
    dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/compl_appr/other'
    dc:description="">
    <preferred>
      <term dc:source="Genomic Standards Consortium MIxS Data Standard"
        dc:title="other"
        xml:lang="en"/>
    </preferred>
    <alternative></alternative>
  </concept>
</thesaurus>

=== gbif/rs.gbif.org/vocabulary/eol/license.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus 
    dc:URI="http://www.eol.org/IPT/vocabulary/license" 
	dc:description="Creative Commons licenses allowed in EOL" 
	dc:title="Licenses EOL Vocabulary"
  dc:issued="2015-02-13"
  xmlns="http://rs.gbif.org/thesaurus/" xmlns:dc="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">

    <concept dc:identifier="http://creativecommons.org/licenses/publicdomain/" 
             dc:URI="http://creativecommons.org/licenses/publicdomain/"    
             dc:relation="http://creativecommons.org/licenses/publicdomain/"    
             dc:description="Public Domain Certification">
        <preferred>
	        <term dc:title="Public Domain" xml:lang="en"/>
        </preferred>
		<alternative></alternative>
    </concept>
    
    <concept dc:identifier="http://creativecommons.org/licenses/by/3.0/" dc:URI="http://creativecommons.org/licenses/by/3.0/" dc:relation="http://creativecommons.org/licenses/by/3.0/" dc:description="Attribution 3.0 Unported">
      <preferred>
        <term dc:title="Attribution 3.0 Unported" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="http://creativecommons.org/licenses/by-nc/3.0/" dc:URI="http://creativecommons.org/licenses/by-nc/3.0/" dc:relation="http://creativecommons.org/licenses/by-nc/3.0/" dc:description="Attribution-NonCommercial 3.0 Unported">
      <preferred>
        <term dc:title="Attribution-NonCommercial 3.0 Unported" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="http://creativecommons.org/licenses/by-sa/3.0/" dc:URI="http://creativecommons.org/licenses/by-sa/3.0/" dc:relation="http://creativecommons.org/licenses/by-sa/3.0/" dc:description="Attribution-ShareAlike 3.0 Unported">
      <preferred>
        <term dc:title="Attribution-ShareAlike 3.0 Unported" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="http://creativecommons.org/licenses/by-nc-sa/3.0/" dc:URI="http://creativecommons.org/licenses/by-nc-sa/3.0/" dc:relation="http://creativecommons.org/licenses/by-nc-sa/3.0/" dc:description="Attribution-NonCommercial-ShareAlike 3.0 Unported">
      <preferred>
        <term dc:title="Attribution-NonCommercial-ShareAlike 3.0 Unported" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>


    <concept dc:identifier="http://creativecommons.org/licenses/by/2.5/" dc:URI="http://creativecommons.org/licenses/by/2.5/" dc:relation="http://creativecommons.org/licenses/by/2.5/" dc:description="Attribution 2.5 Generic">
      <preferred>
        <term dc:title="Attribution 2.5 Generic" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="http://creativecommons.org/licenses/by-nc/2.5/" dc:URI="http://creativecommons.org/licenses/by-nc/2.5/" dc:relation="http://creativecommons.org/licenses/by-nc/2.5/" dc:description="Attribution-NonCommercial 2.5 Generic">
      <preferred>
        <term dc:title="Attribution-NonCommercial 2.5 Generic" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="http://creativecommons.org/licenses/by-sa/2.5/" dc:URI="http://creativecommons.org/licenses/by-sa/2.5/" dc:relation="http://creativecommons.org/licenses/by-sa/2.5/" dc:description="Attribution-ShareAlike 2.5 Generic">
      <preferred>
        <term dc:title="Attribution-ShareAlike 2.5 Generic" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="http://creativecommons.org/licenses/by-nc-sa/2.5/" dc:URI="http://creativecommons.org/licenses/by-nc-sa/2.5/" dc:relation="http://creativecommons.org/licenses/by-nc-sa/2.5/" dc:description="Attribution-NonCommercial-ShareAlike 2.5 Generic">
      <preferred>
        <term dc:title="Attribution-NonCommercial-ShareAlike 2.5 Generic" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>


    <concept dc:identifier="http://creativecommons.org/licenses/by/2.0/" dc:URI="http://creativecommons.org/licenses/by/2.0/" dc:relation="http://creativecommons.org/licenses/by/2.0/" dc:description="Attribution 2.0 Generic">
      <preferred>
        <term dc:title="Attribution 2.0 Generic" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="http://creativecommons.org/licenses/by-nc/2.0/" dc:URI="http://creativecommons.org/licenses/by-nc/2.0/" dc:relation="http://creativecommons.org/licenses/by-nc/2.0/" dc:description="Attribution-NonCommercial 2.0 Generic">
      <preferred>
        <term dc:title="Attribution-NonCommercial 2.0 Generic" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="http://creativecommons.org/licenses/by-sa/2.0/" dc:URI="http://creativecommons.org/licenses/by-sa/2.0/" dc:relation="http://creativecommons.org/licenses/by-sa/2.0/" dc:description="Attribution-ShareAlike 2.0 Generic">
      <preferred>
        <term dc:title="Attribution-ShareAlike 2.0 Generic" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="http://creativecommons.org/licenses/by-nc-sa/2.0/" dc:URI="http://creativecommons.org/licenses/by-nc-sa/2.0/" dc:relation="http://creativecommons.org/licenses/by-nc-sa/2.0/" dc:description="Attribution-NonCommercial-ShareAlike 2.0 Generic">
      <preferred>
        <term dc:title="Attribution-NonCommercial-ShareAlike 2.0 Generic" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>


    <concept dc:identifier="http://creativecommons.org/licenses/by/1.0/" dc:URI="http://creativecommons.org/licenses/by/1.0/" dc:relation="http://creativecommons.org/licenses/by/1.0/" dc:description="Attribution 1.0 Generic">
      <preferred>
        <term dc:title="Attribution 1.0 Generic" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="http://creativecommons.org/licenses/by-nc/1.0/" dc:URI="http://creativecommons.org/licenses/by-nc/1.0/" dc:relation="http://creativecommons.org/licenses/by-nc/1.0/" dc:description="Attribution-NonCommercial 1.0 Generic">
      <preferred>
        <term dc:title="Attribution-NonCommercial 1.0 Generic" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="http://creativecommons.org/licenses/by-sa/1.0/" dc:URI="http://creativecommons.org/licenses/by-sa/1.0/" dc:relation="http://creativecommons.org/licenses/by-sa/1.0/" dc:description="Attribution-ShareAlike 1.0 Generic">
      <preferred>
        <term dc:title="Attribution-ShareAlike 1.0 Generic" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>

    <concept dc:identifier="http://creativecommons.org/licenses/by-nc-sa/1.0/" dc:URI="http://creativecommons.org/licenses/by-nc-sa/1.0/" dc:relation="http://creativecommons.org/licenses/by-nc-sa/1.0/" dc:description="Attribution-NonCommercial-ShareAlike 1.0 Generic">
      <preferred>
        <term dc:title="Attribution-NonCommercial-ShareAlike 1.0 Generic" xml:lang="en"/>
      </preferred>
      <alternative></alternative>
    </concept>


</thesaurus>

=== gbif/rs.gbif.org/deprecated/vocabulary/germplasm/0.1/TypeOfStorage.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus 
    dc:URI="http://rs.nordgen.org/dwc/germplasm/0.1/vocabulary/TypeOfStorage"
    dc:description="Controlled vocabulary following the Multi-Crop Passport standard for term 27, Type of germplasm storage (STORAGE)." 
    dc:title="Type of germplasm storage"
    xmlns="http://rs.gbif.org/thesaurus/" 
    xmlns:dc="http://purl.org/dc/terms/" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://rs.gbif.org/thesaurus/ http://rs.gbif.org/schema/thesaurus.xsd">

    <concept dc:identifier="10" 
        dc:URI="http://rs.nordgen.org/dwc/germplasm/0.1/vocabulary/TypeOfStorage/10" 
        dc:description="Seed collection">
        <preferred>
            <term dc:source="Germplasm" dc:title="Seed collection (10)" xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>

    <concept dc:identifier="11" 
        dc:URI="http://rs.nordgen.org/dwc/germplasm/0.1/vocabulary/TypeOfStorage/11" 
        dc:description="Short term">
        <preferred>
            <term dc:source="Germplasm" dc:title="Short term (11)" xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>

    <concept dc:identifier="12" 
        dc:URI="http://rs.nordgen.org/dwc/germplasm/0.1/vocabulary/TypeOfStorage/12" 
        dc:description="Medium term">
        <preferred>
            <term dc:source="Germplasm" dc:title="Medium term (12)" xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>

    <concept dc:identifier="13" 
        dc:URI="http://rs.nordgen.org/dwc/germplasm/0.1/vocabulary/TypeOfStorage/13" 
        dc:description="Long term">
        <preferred>
            <term dc:source="Germplasm" dc:title="Long term (13)" xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>

    <concept dc:identifier="20" 
        dc:URI="http://rs.nordgen.org/dwc/germplasm/0.1/vocabulary/TypeOfStorage/20" 
        dc:description="Field collection">
        <preferred>
            <term dc:source="Germplasm" dc:title="Field collection (20)" xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>

    <concept dc:identifier="30" 
        dc:URI="http://rs.nordgen.org/dwc/germplasm/0.1/vocabulary/TypeOfStorage/30" 
        dc:description="In vitro collection. Slow growth.">
        <preferred>
            <term dc:source="Germplasm" dc:title="In vitro collection (30)" xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>

    <concept dc:identifier="40" 
        dc:URI="http://rs.nordgen.org/dwc/germplasm/0.1/vocabulary/TypeOfStorage/40" 
        dc:description="Cryopreserved collection">
        <preferred>
            <term dc:source="Germplasm" dc:title="Cryopreserved collection (40)" xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>

    <concept dc:identifier="99" 
        dc:URI="http://rs.nordgen.org/dwc/germplasm/0.1/vocabulary/TypeOfStorage/99" 
        dc:description="Other type of germplasm storage, elaborate in remarks field">
        <preferred>
            <term dc:source="Germplasm" dc:title="Other (99)" xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>

</thesaurus>
