=== gbif/rs.gbif.org/schema/thesaurus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://rs.gbif.org/thesaurus/"
	xmlns:dc="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/"
	xmlns:xml="http://www.w3.org/XML/1998/namespace" targetNamespace="http://rs.gbif.org/thesaurus/"
	elementFormDefault="qualified">
	<xs:import namespace="http://purl.org/dc/terms/" schemaLocation="dc.xsd"/>
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"
		schemaLocation="http://rs.gbif.org/schema/xml.xsd"/>
	<xs:element name="thesaurus">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="concept" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute ref="dc:URI" use="required"/>
			<xs:attribute ref="dc:title" use="required"/>
			<xs:attribute ref="dc:issued" use="required">
				<xs:annotation>
					<xs:documentation>The date that the vocabulary (version) was officially released.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:description" use="optional"/>
			<xs:attribute ref="dc:relation" use="optional"/>
			<xs:attribute ref="dc:subject" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="concept">
		<xs:complexType>

			<xs:sequence>
				<!-- Many titles per language for synonyms -->
				<xs:element name="preferred">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="term" maxOccurs="unbounded" minOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<!-- Many titles per language for synonyms -->
				<xs:element name="alternative" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="term" maxOccurs="unbounded" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute ref="dc:URI" use="required">
				<xs:annotation>
					<xs:documentation>The proper full URI. Preferably pointing to an
						RDF document in an ontology</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:description" use="optional"/>
			<xs:attribute ref="dc:relation" use="optional"/>
			<xs:attribute name="comments" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Recommendations for the content for the property.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:subject" use="optional"/>
			<xs:attribute ref="dc:identifier" use="required">
				<xs:annotation>
					<xs:documentation>A short code locally unique within a vocabulary
						as identified by the dc:type attribute.
						Should be language neutral as much as possible. E.g. DE for Germany or
						familia for the family rank</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:issued" use="optional"/>
			<xs:anyAttribute processContents="lax"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="term">
		<xs:complexType>
			<xs:attribute ref="dc:title" use="required">
				<xs:annotation>
					<xs:documentation>The term itself</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="xml:lang" use="optional">
				<xs:annotation>
					<xs:documentation>ISO 2 letter language code only!</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:source" use="optional">
				<xs:annotation>
					<xs:documentation>The source where the term originated from
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:modified" use="optional"/>
			<xs:anyAttribute processContents="lax"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gbif/rs.gbif.org/sandbox/vocabulary/mixs/contam_screen_input.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/contam_screen_input/'
  dc:description="The contamination screening input Vocabulary is a recommended set of values to use for the contam_screen_input term in the MIxS Extension."
  dc:title="Genomic Standards Consortium contamination screening input Vocabulary"
  dc:issued="2020-04-24"
  dc:relation=""
  xmlns="http://rs.gbif.org/thesaurus/"
  xmlns:dc="http://purl.org/dc/terms/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">
  <concept dc:identifier="reads"
    dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/contam_screen_input/reads'
    dc:description="">
    <preferred>
      <term dc:source="Genomic Standards Consortium MIxS Data Standard"
        dc:title="reads"
        xml:lang="en"/>
    </preferred>
    <alternative></alternative>
  </concept>
  <concept dc:identifier="contigs"
    dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/contam_screen_input/contigs'
    dc:description="">
    <preferred>
      <term dc:source="Genomic Standards Consortium MIxS Data Standard"
        dc:title=" contigs"
        xml:lang="en"/>
    </preferred>
    <alternative></alternative>
  </concept>
</thesaurus>

=== gbif/rs.gbif.org/vocabulary/gbif/dataset_subtype.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus
    dc:URI="http://rs.gbif.org/vocabulary/gbif/datasetSubtype"
    dc:description="Vocabulary for Checklist or Occurrence dataset subtypes used in the GBIF Network."
    dc:title="GBIF Dataset Subtype Vocabulary"
    dc:issued="2015-02-13"
    xmlns="http://rs.gbif.org/thesaurus/" xmlns:dc="http://purl.org/dc/terms/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">
    <concept dc:identifier="taxonomicAuthority" dc:URI="http://rs.gbif.org/vocabulary/gbif/datasetSubtype/taxonomicAuthority"
        dc:relation=""
        dc:description="EN: A taxonomic checklist that is authoritative in its classification and synonymy. ZH: 指的是分類體系與同物異名關係">
        <preferred>
            <term dc:title="Taxonomic Authority" xml:lang="en"/>
            <term dc:title="Autoridad Taxonómica" xml:lang="es"/>
            <term dc:title="Autorité Taxonomique" xml:lang="fr"/>
            <term dc:title="分類權威" xml:lang="zh"/>
            <term dc:title="Autoridade Taxonômica" xml:lang="pt"/>
            <term dc:title="正式な生物分類" xml:lang="ja"/>
            <term dc:title="Таксономический авторитет" xml:lang="ru"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="nomenclatorAuthority" dc:URI="http://rs.gbif.org/vocabulary/gbif/datasetSubtype/nomenclatorAuthority"
        dc:relation=""
        dc:description="EN: A nomenclatoral checklist that is authoritative in the pure names and publication information. ZH: 指的是命名與發表資訊，著重於該學名的合法性與有效性">
        <preferred>
            <term dc:title="Nomenclator Authority" xml:lang="en"/>
            <term dc:title="Autoridad Nomenclatural" xml:lang="es"/>
            <term dc:title="Autorité de Nomenclature" xml:lang="fr"/>
            <term dc:title="命名權威" xml:lang="zh"/>
            <term dc:title="Autoridade Nomenclatural" xml:lang="pt"/>
            <term dc:title="正式な学名命名" xml:lang="ja"/>
            <term dc:title="Номенклатурный авторитет" xml:lang="ru"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="inventoryThematic" dc:URI="http://rs.gbif.org/vocabulary/gbif/datasetSubtype/inventoryThematic"
        dc:relation=""
        dc:description="a thematic checklist that has a theme for grouping names, e.g. parasites of elephants.">
        <preferred>
            <term dc:title="Inventory Thematic" xml:lang="en"/>
            <term dc:title="Inventario Temático" xml:lang="es"/>
            <term dc:title="Inventaire Thématique" xml:lang="fr"/>
            <term dc:title="主題性清冊" xml:lang="zh"/>
            <term dc:title="Inventário Temático" xml:lang="pt"/>
            <term dc:title="主題目録" xml:lang="ja"/>
            <term dc:title="Тематическая инвентаризация" xml:lang="ru"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="inventoryRegional" dc:URI="http://rs.gbif.org/vocabulary/gbif/datasetSubtype/inventoryRegional"
        dc:relation=""
        dc:description="a regional checklist that has a regional commonality in grouping names, e.g. species in a protected area.">
        <preferred>
            <term dc:title="Inventory Regional" xml:lang="en"/>
            <term dc:title="Inventario Regional" xml:lang="es"/>
            <term dc:title="Inventaire Régional" xml:lang="fr"/>
            <term dc:title="區域性清冊" xml:lang="zh"/>
            <term dc:title="Inventário Regional" xml:lang="pt"/>
            <term dc:title="地域目録" xml:lang="ja"/>
            <term dc:title="Региональная инвентаризация" xml:lang="ru"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="globalSpeciesDataset" dc:URI="http://rs.gbif.org/vocabulary/gbif/datasetSubtype/globalSpeciesDataset"
        dc:relation=""
        dc:description="A taxonomic checklist with a global, spatial coverage. This subtype is used in particular by the catalogue of life to assemble its aggregated checklist.">
        <preferred>
            <term dc:title="Global Species Dataset" xml:lang="en"/>
            <term dc:title="Recurso Mundial de Especies" xml:lang="es"/>
            <term dc:title="Ressource Mondiale des Espèces" xml:lang="fr"/>
            <term dc:title="全球物種資料集" xml:lang="zh"/>
            <term dc:title="Conjunto de Dados Mundial de Espécies" xml:lang="pt"/>
            <term dc:title="地球規模生物種データセット" xml:lang="ja"/>
            <term dc:title="Набор глобальных данных" xml:lang="ru"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="derivedFromOccurrence" dc:URI="http://rs.gbif.org/vocabulary/gbif/datasetSubtype/derivedFromOccurrence"
        dc:relation=""
        dc:description="A taxonomic checklist that has been derived from data that was originally occurrence data.">
        <preferred>
            <term dc:title="Derived from Occurrence" xml:lang="en"/>
            <term dc:title="Derivado de Registros Biológicos" xml:lang="es"/>
            <term dc:title="Dérivée de Données d'Occurrences" xml:lang="fr"/>
            <term dc:title="取自物種出現紀錄" xml:lang="zh"/>
            <term dc:title="Derivado de Ocorrência" xml:lang="pt"/>
            <term dc:title="オカレンス由来の生物分類" xml:lang="ja"/>
            <term dc:title="На основе находок" xml:lang="ru"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="specimen" dc:URI="http://rs.gbif.org/vocabulary/gbif/datasetSubtype/specimen"
        dc:relation=""
        dc:description="Specimen data. Possible museum collection.">
        <preferred>
            <term dc:title="Specimen" xml:lang="en"/>
            <term dc:title="Ejemplar" xml:lang="es"/>
            <term dc:title="Spécimen" xml:lang="fr"/>
            <term dc:title="標本" xml:lang="zh"/>
            <term dc:title="Espécime" xml:lang="pt"/>
            <term dc:title="標本" xml:lang="ja"/>
            <term dc:title="Образец" xml:lang="ru"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
    <concept dc:identifier="observation" dc:URI="http://rs.gbif.org/vocabulary/gbif/datasetSubtype/observation"
        dc:relation=""
        dc:description="Observation data. Possible monitoring and field observations.">
        <preferred>
            <term dc:title="Observation" xml:lang="en"/>
            <term dc:title="Observación" xml:lang="es"/>
            <term dc:title="Observation" xml:lang="fr"/>
            <term dc:title="觀測" xml:lang="zh"/>
            <term dc:title="Observação" xml:lang="pt"/>
            <term dc:title="観察" xml:lang="ja"/>
            <term dc:title="Наблюдение" xml:lang="ru"/>
        </preferred>
        <alternative>
        </alternative>
    </concept>
</thesaurus>

=== gbif/rs.gbif.org/sandbox/vocabulary/mixs/tax_ident.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/tax_ident/'
  dc:description="The taxonomic identity marker Vocabulary is a recommended set of values to use for the tax_ident term in the MIxS Extension."
  dc:title="Genomic Standards Consortium taxonomic identity marker Vocabulary"
  dc:issued="2020-04-24"
  dc:relation=""
  xmlns="http://rs.gbif.org/thesaurus/"
  xmlns:dc="http://purl.org/dc/terms/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">
  <concept dc:identifier="16_s_r_rna_gene"
    dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/tax_ident/16_s_r_rna_gene'
    dc:description="">
    <preferred>
      <term dc:source="Genomic Standards Consortium MIxS Data Standard"
        dc:title="16S rRNA gene"
        xml:lang="en"/>
    </preferred>
    <alternative></alternative>
  </concept>
  <concept dc:identifier="multi_marker_approach"
    dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/tax_ident/multi_marker_approach'
    dc:description="">
    <preferred>
      <term dc:source="Genomic Standards Consortium MIxS Data Standard"
        dc:title="multi-marker approach"
        xml:lang="en"/>
    </preferred>
    <alternative></alternative>
  </concept>
  <concept dc:identifier="other"
    dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/tax_ident/other'
    dc:description="">
    <preferred>
      <term dc:source="Genomic Standards Consortium MIxS Data Standard"
        dc:title="other"
        xml:lang="en"/>
    </preferred>
    <alternative></alternative>
  </concept>
</thesaurus>

=== gbif/rs.gbif.org/vocabulary/dwc/basis_of_record_2023-09-14.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='/style/human.xsl'?>
<thesaurus
  dc:URI='http://rs.tdwg.org/dwc/dwctype/'
  dc:description='The specific nature of the data record.'
  dc:title='Darwin Core Basis of Record Vocabulary'
  dc:issued='2023-09-14'
  dc:relation='https://dwc.tdwg.org/terms/#dwc:basisOfRecord'
  xmlns='http://rs.gbif.org/thesaurus/'
  xmlns:dc='http://purl.org/dc/terms/'
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:schemaLocation='http://rs.gbif.org/thesaurus/ http://rs.gbif.org/schema/thesaurus.xsd'>

  <concept
    dc:identifier='PreservedSpecimen'
	dc:URI='http://rs.tdwg.org/dwc/dwctype/PreservedSpecimen'
	dc:subject='http://rs.tdwg.org/dwc/terms/PreservedSpecimen'
    dc:relation='https://dwc.tdwg.org/terms/#preservedspecimen'
    dc:issued='2018-09-06'
    comments=''
    dc:description='A specimen that has been preserved.'>
    <preferred>
      <term dc:source='Darwin Core' dc:title='Preserved Specimen' xml:lang='en'/>
      <term dc:source='Darwin Core' dc:title='Espécime Preservado' xml:lang='pt'/>
      <term dc:source='Darwin Core' dc:title='Espécimen preservado' xml:lang='es'/>
      <term dc:source='Darwin Core' dc:title='保存標本' xml:lang='ja'/>
    </preferred>
    <alternative>
    </alternative>
  </concept>

  <concept
    dc:identifier='FossilSpecimen'
	dc:URI='http://rs.tdwg.org/dwc/dwctype/FossilSpecimen'
	dc:subject='http://rs.tdwg.org/dwc/terms/FossilSpecimen'
    dc:relation='https://dwc.tdwg.org/terms/#fossilspecimen'
    dc:issued='2018-09-06'
    comments=''
    dc:description='A preserved specimen that is a fossil.'>
    <preferred>
      <term dc:source='Darwin Core' dc:title='Fossil Specimen' xml:lang='en'/>
      <term dc:source='Darwin Core' dc:title='Espécime Fóssil' xml:lang='pt'/>
      <term dc:source='Darwin Core' dc:title='Espécimen fósil' xml:lang='es'/>
      <term dc:source='Darwin Core' dc:title='化石標本' xml:lang='ja'/>
    </preferred>
    <alternative>
    </alternative>
  </concept>

  <concept
    dc:identifier='LivingSpecimen'
	dc:URI='http://rs.tdwg.org/dwc/dwctype/LivingSpecimen'
	dc:subject='http://rs.tdwg.org/dwc/terms/LivingSpecimen'
    dc:relation='https://dwc.tdwg.org/terms/#livingspecimen'
    dc:issued='2018-09-06'
    comments=''
    dc:description='A specimen that is alive.'>
    <preferred>
      <term dc:source='Darwin Core' dc:title='Living Specimen' xml:lang='en'/>
      <term dc:source='Darwin Core' dc:title='Espécime Vivo' xml:lang='pt'/>
      <term dc:source='Darwin Core' dc:title='Espécimen vivo' xml:lang='es'/>
      <term dc:source='Darwin Core' dc:title='生体標本' xml:lang='ja'/>
    </preferred>
    <alternative>
    </alternative>
  </concept>

  <concept
    dc:identifier='HumanObservation'
	dc:URI='http://rs.tdwg.org/dwc/dwctype/HumanObservation'
	dc:subject='http://rs.tdwg.org/dwc/terms/HumanObservation'
    dc:relation='https://dwc.tdwg.org/terms/#humanobservation'
    dc:issued='2018-09-06'
    comments=''
    dc:description='An output of a human observation process.'>
    <preferred>
      <term dc:source='Darwin Core' dc:title='Human Observation' xml:lang='en'/>
      <term dc:source='Darwin Core' dc:title='Observação por Humano' xml:lang='pt'/>
      <term dc:source='Darwin Core' dc:title='Observación humana' xml:lang='es'/>
      <term dc:source='Darwin Core' dc:title='人による観察' xml:lang='ja'/>
    </preferred>
    <alternative>
    </alternative>
  </concept>

  <concept
    dc:identifier='MachineObservation'
	dc:URI='http://rs.tdwg.org/dwc/dwctype/MachineObservation'
	dc:subject='http://rs.tdwg.org/dwc/terms/MachineObservation'
    dc:relation='https://dwc.tdwg.org/terms/#machineobservation'
    dc:issued='2018-09-06'
    comments=''
    dc:description='An output of a machine observation process.'>
    <preferred>
      <term dc:source='Darwin Core' dc:title='Machine Observation' xml:lang='en'/>
      <term dc:source='Darwin Core' dc:title='Observação por Máquina' xml:lang='pt'/>
      <term dc:source='Darwin Core' dc:title='Observación con máquina' xml:lang='es'/>
      <term dc:source='Darwin Core' dc:title='機械観測' xml:lang='ja'/>
    </preferred>
    <alternative>
    </alternative>
  </concept>

  <concept
    dc:identifier='MaterialEntity'
	dc:URI='http://rs.tdwg.org/dwc/dwctype/MaterialEntity'
	dc:subject='http://rs.tdwg.org/dwc/terms/MaterialEntity'
    dc:relation='https://dwc.tdwg.org/terms/#materialentity'
    dc:issued='2023-09-14'
    comments=''
    dc:description='An entity that can be identified, exists for some period of time, and consists in whole or in part of physical matter while it exists.'>
    <preferred>
      <term dc:source='Darwin Core' dc:title='Material Entity' xml:lang='en'/>
      <term dc:source='Darwin Core' dc:title='Entidad Material' xml:lang='pt'/>
      <term dc:source='Darwin Core' dc:title='Entidade Material' xml:lang='es'/>
      <term dc:source='Darwin Core' dc:title='物質的な実体' xml:lang='ja'/>
    </preferred>
    <alternative>
    </alternative>
  </concept>

  <concept
    dc:identifier='MaterialSample'
	dc:URI='http://rs.tdwg.org/dwc/dwctype/MaterialSample'
	dc:subject='http://rs.tdwg.org/dwc/terms/MaterialSample'
    dc:relation='https://dwc.tdwg.org/terms/#materialsample'
    dc:issued='2023-09-14'
    comments=''
    dc:description='A material entity that represents an entity of interest in whole or in part.'>
    <preferred>
      <term dc:source='Darwin Core' dc:title='Material Sample' xml:lang='en'/>
      <term dc:source='Darwin Core' dc:title='Amostra' xml:lang='pt'/>
      <term dc:source='Darwin Core' dc:title='Muestra' xml:lang='es'/>
      <term dc:source='Darwin Core' dc:title='試料' xml:lang='ja'/>
    </preferred>
    <alternative>
      <term dc:title='Sample' xml:lang='en'/>
    </alternative>
  </concept>

  <concept
    dc:identifier='Occurrence'
	dc:URI='http://rs.tdwg.org/dwc/dwctype/Occurrence'
	dc:subject='http://rs.tdwg.org/dwc/terms/Occurrence'
    dc:relation='https://dwc.tdwg.org/terms/#occurrence'
    dc:issued='2018-09-06'
    comments=''
    dc:description='An existence of an Organism (sensu http://rs.tdwg.org/dwc/terms/Organism) at a particular place at a particular time.'>
    <preferred>
      <term dc:source='Darwin Core' dc:title='Occurrence' xml:lang='en'/>
      <term dc:source='Darwin Core' dc:title='Ocorrência' xml:lang='pt'/>
      <term dc:source='Darwin Core' dc:title='Observación' xml:lang='es'/>
      <term dc:source='Darwin Core' dc:title='オカレンス' xml:lang='ja'/>
    </preferred>
    <alternative>
    </alternative>
  </concept>

  <concept
    dc:identifier='MaterialCitation'
	dc:URI='http://rs.tdwg.org/dwc/dwctype/MaterialCitation'
	dc:subject='http://rs.tdwg.org/dwc/terms/MaterialCitation'
    dc:relation='https://dwc.tdwg.org/terms/#materialcitation'
    dc:issued='2021-07-15'
    comments=''
    dc:description='A reference to or citation of one, a part of, or multiple specimens in scholarly publications.'>
    <preferred>
      <term dc:source='Darwin Core' dc:title='Material Citation' xml:lang='en'/>
    </preferred>
    <alternative>
      <term dc:title='Literature' xml:lang='en'/>
    </alternative>
  </concept>

</thesaurus>

=== gbif/rs.gbif.org/sandbox/vocabulary/mixs/virus_enrich_appr.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/virus_enrich_appr/'
    dc:description="The virus enrichment approach Vocabulary is a recommended set of values to use for the virus_enrich_appr term in the MIxS Extension."
    dc:title="Genomic Standards Consortium virus enrichment approach Vocabulary"
    dc:issued="2020-04-24"
    dc:relation=""
    xmlns="http://rs.gbif.org/thesaurus/"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">
    <concept dc:identifier="filtration"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/virus_enrich_appr/filtration'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="filtration"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="ultrafiltration"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/virus_enrich_appr/ultrafiltration'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="ultrafiltration"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="centrifugation"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/virus_enrich_appr/centrifugation'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="centrifugation"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="ultracentrifugation"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/virus_enrich_appr/ultracentrifugation'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="ultracentrifugation"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="peg_precipitation"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/virus_enrich_appr/peg_precipitation'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="PEG Precipitation"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="fe_cl_precipitation"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/virus_enrich_appr/fe_cl_precipitation'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="FeCl Precipitation"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="cs_cl_density_gradient"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/virus_enrich_appr/cs_cl_density_gradient'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="CsCl density gradient"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="DNAse"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/virus_enrich_appr/DNAse'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="DNAse"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="RNAse"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/virus_enrich_appr/RNAse'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="RNAse"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="targeted_sequence_capture"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/virus_enrich_appr/targeted_sequence_capture'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="targeted sequence capture"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="other"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/virus_enrich_appr/other'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="other"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
    <concept dc:identifier="none"
        dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/virus_enrich_appr/none'
        dc:description="">
        <preferred>
            <term dc:source="Genomic Standards Consortium MIxS Data Standard"
                dc:title="none"
                xml:lang="en"/>
        </preferred>
        <alternative></alternative>
    </concept>
</thesaurus>

=== gbif/rs.gbif.org/sandbox/vocabulary/mixs/detec_type.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/detec_type/'
  dc:description="The detection type Vocabulary is a recommended set of values to use for the detec_type term in the MIxS Extension."
  dc:title="Genomic Standards Consortium detection type Vocabulary"
  dc:issued="2020-04-24"
  dc:relation=""
  xmlns="http://rs.gbif.org/thesaurus/"
  xmlns:dc="http://purl.org/dc/terms/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">
  <concept dc:identifier="independent_sequence_uvig"
    dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/detec_type/independent_sequence_uvig'
    dc:description="">
    <preferred>
      <term dc:source="Genomic Standards Consortium MIxS Data Standard"
        dc:title="independent sequence (UViG)"
        xml:lang="en"/>
    </preferred>
    <alternative></alternative>
  </concept>
  <concept dc:identifier="provirus_upvig"
    dc:URI='http://gensc.org/ns/mixs/terms/vocabulary/detec_type/provirus_upvig'
    dc:description="">
    <preferred>
      <term dc:source="Genomic Standards Consortium MIxS Data Standard"
        dc:title="provirus (UpViG)"
        xml:lang="en"/>
    </preferred>
    <alternative></alternative>
  </concept>
</thesaurus>
